// flow-typed signature: fad47791f641cf52a098d10bdf5795e0
// flow-typed version: <<STUB>>/go-ipfs_vhttps://github.com/ipfs/npm-go-ipfs.git#8b0e3d947f0af11a8704760f1f78d7b8a02324aa/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'go-ipfs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'go-ipfs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'go-ipfs/src/download' {
  declare module.exports: any;
}

declare module 'go-ipfs/src/go-platform' {
  declare module.exports: any;
}

declare module 'go-ipfs/src' {
  declare module.exports: any;
}

declare module 'go-ipfs/src/post-install' {
  declare module.exports: any;
}

declare module 'go-ipfs/test/download' {
  declare module.exports: any;
}

declare module 'go-ipfs/test/fixtures/clean' {
  declare module.exports: any;
}

declare module 'go-ipfs/test/install' {
  declare module.exports: any;
}

declare module 'go-ipfs/test/path' {
  declare module.exports: any;
}

// Filename aliases
declare module 'go-ipfs/src/download.js' {
  declare module.exports: $Exports<'go-ipfs/src/download'>;
}
declare module 'go-ipfs/src/go-platform.js' {
  declare module.exports: $Exports<'go-ipfs/src/go-platform'>;
}
declare module 'go-ipfs/src/index' {
  declare module.exports: $Exports<'go-ipfs/src'>;
}
declare module 'go-ipfs/src/index.js' {
  declare module.exports: $Exports<'go-ipfs/src'>;
}
declare module 'go-ipfs/src/post-install.js' {
  declare module.exports: $Exports<'go-ipfs/src/post-install'>;
}
declare module 'go-ipfs/test/download.js' {
  declare module.exports: $Exports<'go-ipfs/test/download'>;
}
declare module 'go-ipfs/test/fixtures/clean.js' {
  declare module.exports: $Exports<'go-ipfs/test/fixtures/clean'>;
}
declare module 'go-ipfs/test/install.js' {
  declare module.exports: $Exports<'go-ipfs/test/install'>;
}
declare module 'go-ipfs/test/path.js' {
  declare module.exports: $Exports<'go-ipfs/test/path'>;
}
