// flow-typed signature: db3312a837aebf20b826f568737e0697
// flow-typed version: <<STUB>>/go-ipfs-dep_v^0.4.13/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'go-ipfs-dep'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'go-ipfs-dep' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'go-ipfs-dep/src/bin' {
  declare module.exports: any;
}

declare module 'go-ipfs-dep/src/check-support' {
  declare module.exports: any;
}

declare module 'go-ipfs-dep/src/index' {
  declare module.exports: any;
}

declare module 'go-ipfs-dep/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'go-ipfs-dep/src/bin.js' {
  declare module.exports: $Exports<'go-ipfs-dep/src/bin'>;
}
declare module 'go-ipfs-dep/src/check-support.js' {
  declare module.exports: $Exports<'go-ipfs-dep/src/check-support'>;
}
declare module 'go-ipfs-dep/src/index.js' {
  declare module.exports: $Exports<'go-ipfs-dep/src/index'>;
}
declare module 'go-ipfs-dep/test/index.js' {
  declare module.exports: $Exports<'go-ipfs-dep/test/index'>;
}
