// flow-typed signature: 035a22c0b91b4aa28b7c722ed8b24342
// flow-typed version: <<STUB>>/ipfs-api_v^17.3.0/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ipfs-api'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ipfs-api' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ipfs-api/dist/index' {
  declare module.exports: any;
}

declare module 'ipfs-api/dist/index.min' {
  declare module.exports: any;
}

declare module 'ipfs-api/examples/bundle-browserify/index' {
  declare module.exports: any;
}

declare module 'ipfs-api/examples/bundle-webpack/server' {
  declare module.exports: any;
}

declare module 'ipfs-api/examples/bundle-webpack/src/App' {
  declare module.exports: any;
}

declare module 'ipfs-api/examples/bundle-webpack/src/index' {
  declare module.exports: any;
}

declare module 'ipfs-api/examples/bundle-webpack/webpack.config' {
  declare module.exports: any;
}

declare module 'ipfs-api/examples/files-api/files-api' {
  declare module.exports: any;
}

declare module 'ipfs-api/examples/name-api/index' {
  declare module.exports: any;
}

declare module 'ipfs-api/examples/sub-module/complete-module' {
  declare module.exports: any;
}

declare module 'ipfs-api/examples/sub-module/modules/add/add' {
  declare module.exports: any;
}

declare module 'ipfs-api/examples/sub-module/modules/bitswap/bitswap' {
  declare module.exports: any;
}

declare module 'ipfs-api/examples/sub-module/modules/block/block' {
  declare module.exports: any;
}

declare module 'ipfs-api/examples/sub-module/modules/bootstrap/bootstrap' {
  declare module.exports: any;
}

declare module 'ipfs-api/examples/sub-module/modules/cat/cat' {
  declare module.exports: any;
}

declare module 'ipfs-api/examples/sub-module/modules/commands/commands' {
  declare module.exports: any;
}

declare module 'ipfs-api/examples/sub-module/modules/config/config' {
  declare module.exports: any;
}

declare module 'ipfs-api/examples/sub-module/modules/dht/dht' {
  declare module.exports: any;
}

declare module 'ipfs-api/examples/sub-module/modules/diag/diag' {
  declare module.exports: any;
}

declare module 'ipfs-api/examples/sub-module/modules/files/files' {
  declare module.exports: any;
}

declare module 'ipfs-api/examples/sub-module/modules/get/get' {
  declare module.exports: any;
}

declare module 'ipfs-api/examples/sub-module/modules/id/id' {
  declare module.exports: any;
}

declare module 'ipfs-api/examples/sub-module/modules/key/key' {
  declare module.exports: any;
}

declare module 'ipfs-api/examples/sub-module/modules/log/log' {
  declare module.exports: any;
}

declare module 'ipfs-api/examples/sub-module/modules/ls/ls' {
  declare module.exports: any;
}

declare module 'ipfs-api/examples/sub-module/modules/mount/mount' {
  declare module.exports: any;
}

declare module 'ipfs-api/examples/sub-module/modules/name/name' {
  declare module.exports: any;
}

declare module 'ipfs-api/examples/sub-module/modules/object/object' {
  declare module.exports: any;
}

declare module 'ipfs-api/examples/sub-module/modules/pin/pin' {
  declare module.exports: any;
}

declare module 'ipfs-api/examples/sub-module/modules/ping/ping' {
  declare module.exports: any;
}

declare module 'ipfs-api/examples/sub-module/modules/pubsub/pubsub' {
  declare module.exports: any;
}

declare module 'ipfs-api/examples/sub-module/modules/refs/refs' {
  declare module.exports: any;
}

declare module 'ipfs-api/examples/sub-module/modules/repo/repo' {
  declare module.exports: any;
}

declare module 'ipfs-api/examples/sub-module/modules/swarm/swarm' {
  declare module.exports: any;
}

declare module 'ipfs-api/examples/sub-module/modules/update/update' {
  declare module.exports: any;
}

declare module 'ipfs-api/examples/sub-module/modules/version/version' {
  declare module.exports: any;
}

declare module 'ipfs-api/examples/sub-module/webpack.config' {
  declare module.exports: any;
}

declare module 'ipfs-api/examples/upload-file-via-browser/server' {
  declare module.exports: any;
}

declare module 'ipfs-api/examples/upload-file-via-browser/src/App' {
  declare module.exports: any;
}

declare module 'ipfs-api/examples/upload-file-via-browser/src/index' {
  declare module.exports: any;
}

declare module 'ipfs-api/examples/upload-file-via-browser/webpack.config' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/add' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/bitswap/index' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/bitswap/stat' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/bitswap/unwant' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/bitswap/wantlist' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/block/get' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/block/index' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/block/put' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/block/stat' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/bootstrap/add' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/bootstrap/index' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/bootstrap/list' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/bootstrap/rm' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/cat' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/commands' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/config/get' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/config/index' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/config/replace' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/config/set' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/dht/findpeer' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/dht/findprovs' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/dht/get' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/dht/index' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/dht/provide' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/dht/put' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/dht/query' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/diag/cmds' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/diag/index' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/diag/net' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/diag/sys' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/dns' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/files/add-pull-stream' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/files/add-readable-stream' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/files/add' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/files/cat-pull-stream' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/files/cat-readable-stream' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/files/cat' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/files/cp' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/files/flush' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/files/get-pull-stream' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/files/get-readable-stream' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/files/get' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/files/index' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/files/ls' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/files/mkdir' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/files/mv' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/files/read' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/files/rm' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/files/stat' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/files/write' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/get' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/id' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/index' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/key/export' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/key/gen' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/key/import' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/key/index' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/key/list' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/key/rename' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/key/rm' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/log/index' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/log/level' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/log/ls' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/log/tail' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/ls-pull-stream' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/ls-readable-stream' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/ls' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/mount' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/name/index' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/name/publish' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/name/resolve' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/object/addLink' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/object/appendData' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/object/data' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/object/get' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/object/index' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/object/links' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/object/new' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/object/put' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/object/rmLink' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/object/setData' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/object/stat' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/pin/add' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/pin/index' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/pin/ls' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/pin/rm' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/ping' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/pubsub' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/refs' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/repo/gc' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/repo/index' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/repo/stat' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/stats/bitswap' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/stats/bw' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/stats/index' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/stats/repo' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/swarm/addrs' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/swarm/connect' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/swarm/disconnect' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/swarm/index' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/swarm/localAddrs' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/swarm/peers' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/update' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/util/fs-add' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/util/url-add' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/utils/clean-cid' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/utils/clean-multihash' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/utils/converter' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/utils/default-config' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/utils/load-commands' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/utils/module-config' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/utils/multipart' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/utils/prepare-file' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/utils/progress-stream' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/utils/pubsub-message-stream' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/utils/pubsub-message-utils' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/utils/request' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/utils/send-files-stream' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/utils/send-one-file-multiple-results' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/utils/send-one-file' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/utils/send-request' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/utils/stream-to-json-value' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/utils/stream-to-value' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/utils/stringlist-to-array' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/utils/tar-stream-to-objects' {
  declare module.exports: any;
}

declare module 'ipfs-api/src/version' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ipfs-api/dist/index.js' {
  declare module.exports: $Exports<'ipfs-api/dist/index'>;
}
declare module 'ipfs-api/dist/index.min.js' {
  declare module.exports: $Exports<'ipfs-api/dist/index.min'>;
}
declare module 'ipfs-api/examples/bundle-browserify/index.js' {
  declare module.exports: $Exports<'ipfs-api/examples/bundle-browserify/index'>;
}
declare module 'ipfs-api/examples/bundle-webpack/server.js' {
  declare module.exports: $Exports<'ipfs-api/examples/bundle-webpack/server'>;
}
declare module 'ipfs-api/examples/bundle-webpack/src/App.js' {
  declare module.exports: $Exports<'ipfs-api/examples/bundle-webpack/src/App'>;
}
declare module 'ipfs-api/examples/bundle-webpack/src/index.js' {
  declare module.exports: $Exports<'ipfs-api/examples/bundle-webpack/src/index'>;
}
declare module 'ipfs-api/examples/bundle-webpack/webpack.config.js' {
  declare module.exports: $Exports<'ipfs-api/examples/bundle-webpack/webpack.config'>;
}
declare module 'ipfs-api/examples/files-api/files-api.js' {
  declare module.exports: $Exports<'ipfs-api/examples/files-api/files-api'>;
}
declare module 'ipfs-api/examples/name-api/index.js' {
  declare module.exports: $Exports<'ipfs-api/examples/name-api/index'>;
}
declare module 'ipfs-api/examples/sub-module/complete-module.js' {
  declare module.exports: $Exports<'ipfs-api/examples/sub-module/complete-module'>;
}
declare module 'ipfs-api/examples/sub-module/modules/add/add.js' {
  declare module.exports: $Exports<'ipfs-api/examples/sub-module/modules/add/add'>;
}
declare module 'ipfs-api/examples/sub-module/modules/bitswap/bitswap.js' {
  declare module.exports: $Exports<'ipfs-api/examples/sub-module/modules/bitswap/bitswap'>;
}
declare module 'ipfs-api/examples/sub-module/modules/block/block.js' {
  declare module.exports: $Exports<'ipfs-api/examples/sub-module/modules/block/block'>;
}
declare module 'ipfs-api/examples/sub-module/modules/bootstrap/bootstrap.js' {
  declare module.exports: $Exports<'ipfs-api/examples/sub-module/modules/bootstrap/bootstrap'>;
}
declare module 'ipfs-api/examples/sub-module/modules/cat/cat.js' {
  declare module.exports: $Exports<'ipfs-api/examples/sub-module/modules/cat/cat'>;
}
declare module 'ipfs-api/examples/sub-module/modules/commands/commands.js' {
  declare module.exports: $Exports<'ipfs-api/examples/sub-module/modules/commands/commands'>;
}
declare module 'ipfs-api/examples/sub-module/modules/config/config.js' {
  declare module.exports: $Exports<'ipfs-api/examples/sub-module/modules/config/config'>;
}
declare module 'ipfs-api/examples/sub-module/modules/dht/dht.js' {
  declare module.exports: $Exports<'ipfs-api/examples/sub-module/modules/dht/dht'>;
}
declare module 'ipfs-api/examples/sub-module/modules/diag/diag.js' {
  declare module.exports: $Exports<'ipfs-api/examples/sub-module/modules/diag/diag'>;
}
declare module 'ipfs-api/examples/sub-module/modules/files/files.js' {
  declare module.exports: $Exports<'ipfs-api/examples/sub-module/modules/files/files'>;
}
declare module 'ipfs-api/examples/sub-module/modules/get/get.js' {
  declare module.exports: $Exports<'ipfs-api/examples/sub-module/modules/get/get'>;
}
declare module 'ipfs-api/examples/sub-module/modules/id/id.js' {
  declare module.exports: $Exports<'ipfs-api/examples/sub-module/modules/id/id'>;
}
declare module 'ipfs-api/examples/sub-module/modules/key/key.js' {
  declare module.exports: $Exports<'ipfs-api/examples/sub-module/modules/key/key'>;
}
declare module 'ipfs-api/examples/sub-module/modules/log/log.js' {
  declare module.exports: $Exports<'ipfs-api/examples/sub-module/modules/log/log'>;
}
declare module 'ipfs-api/examples/sub-module/modules/ls/ls.js' {
  declare module.exports: $Exports<'ipfs-api/examples/sub-module/modules/ls/ls'>;
}
declare module 'ipfs-api/examples/sub-module/modules/mount/mount.js' {
  declare module.exports: $Exports<'ipfs-api/examples/sub-module/modules/mount/mount'>;
}
declare module 'ipfs-api/examples/sub-module/modules/name/name.js' {
  declare module.exports: $Exports<'ipfs-api/examples/sub-module/modules/name/name'>;
}
declare module 'ipfs-api/examples/sub-module/modules/object/object.js' {
  declare module.exports: $Exports<'ipfs-api/examples/sub-module/modules/object/object'>;
}
declare module 'ipfs-api/examples/sub-module/modules/pin/pin.js' {
  declare module.exports: $Exports<'ipfs-api/examples/sub-module/modules/pin/pin'>;
}
declare module 'ipfs-api/examples/sub-module/modules/ping/ping.js' {
  declare module.exports: $Exports<'ipfs-api/examples/sub-module/modules/ping/ping'>;
}
declare module 'ipfs-api/examples/sub-module/modules/pubsub/pubsub.js' {
  declare module.exports: $Exports<'ipfs-api/examples/sub-module/modules/pubsub/pubsub'>;
}
declare module 'ipfs-api/examples/sub-module/modules/refs/refs.js' {
  declare module.exports: $Exports<'ipfs-api/examples/sub-module/modules/refs/refs'>;
}
declare module 'ipfs-api/examples/sub-module/modules/repo/repo.js' {
  declare module.exports: $Exports<'ipfs-api/examples/sub-module/modules/repo/repo'>;
}
declare module 'ipfs-api/examples/sub-module/modules/swarm/swarm.js' {
  declare module.exports: $Exports<'ipfs-api/examples/sub-module/modules/swarm/swarm'>;
}
declare module 'ipfs-api/examples/sub-module/modules/update/update.js' {
  declare module.exports: $Exports<'ipfs-api/examples/sub-module/modules/update/update'>;
}
declare module 'ipfs-api/examples/sub-module/modules/version/version.js' {
  declare module.exports: $Exports<'ipfs-api/examples/sub-module/modules/version/version'>;
}
declare module 'ipfs-api/examples/sub-module/webpack.config.js' {
  declare module.exports: $Exports<'ipfs-api/examples/sub-module/webpack.config'>;
}
declare module 'ipfs-api/examples/upload-file-via-browser/server.js' {
  declare module.exports: $Exports<'ipfs-api/examples/upload-file-via-browser/server'>;
}
declare module 'ipfs-api/examples/upload-file-via-browser/src/App.js' {
  declare module.exports: $Exports<'ipfs-api/examples/upload-file-via-browser/src/App'>;
}
declare module 'ipfs-api/examples/upload-file-via-browser/src/index.js' {
  declare module.exports: $Exports<'ipfs-api/examples/upload-file-via-browser/src/index'>;
}
declare module 'ipfs-api/examples/upload-file-via-browser/webpack.config.js' {
  declare module.exports: $Exports<'ipfs-api/examples/upload-file-via-browser/webpack.config'>;
}
declare module 'ipfs-api/src/add.js' {
  declare module.exports: $Exports<'ipfs-api/src/add'>;
}
declare module 'ipfs-api/src/bitswap/index.js' {
  declare module.exports: $Exports<'ipfs-api/src/bitswap/index'>;
}
declare module 'ipfs-api/src/bitswap/stat.js' {
  declare module.exports: $Exports<'ipfs-api/src/bitswap/stat'>;
}
declare module 'ipfs-api/src/bitswap/unwant.js' {
  declare module.exports: $Exports<'ipfs-api/src/bitswap/unwant'>;
}
declare module 'ipfs-api/src/bitswap/wantlist.js' {
  declare module.exports: $Exports<'ipfs-api/src/bitswap/wantlist'>;
}
declare module 'ipfs-api/src/block/get.js' {
  declare module.exports: $Exports<'ipfs-api/src/block/get'>;
}
declare module 'ipfs-api/src/block/index.js' {
  declare module.exports: $Exports<'ipfs-api/src/block/index'>;
}
declare module 'ipfs-api/src/block/put.js' {
  declare module.exports: $Exports<'ipfs-api/src/block/put'>;
}
declare module 'ipfs-api/src/block/stat.js' {
  declare module.exports: $Exports<'ipfs-api/src/block/stat'>;
}
declare module 'ipfs-api/src/bootstrap/add.js' {
  declare module.exports: $Exports<'ipfs-api/src/bootstrap/add'>;
}
declare module 'ipfs-api/src/bootstrap/index.js' {
  declare module.exports: $Exports<'ipfs-api/src/bootstrap/index'>;
}
declare module 'ipfs-api/src/bootstrap/list.js' {
  declare module.exports: $Exports<'ipfs-api/src/bootstrap/list'>;
}
declare module 'ipfs-api/src/bootstrap/rm.js' {
  declare module.exports: $Exports<'ipfs-api/src/bootstrap/rm'>;
}
declare module 'ipfs-api/src/cat.js' {
  declare module.exports: $Exports<'ipfs-api/src/cat'>;
}
declare module 'ipfs-api/src/commands.js' {
  declare module.exports: $Exports<'ipfs-api/src/commands'>;
}
declare module 'ipfs-api/src/config/get.js' {
  declare module.exports: $Exports<'ipfs-api/src/config/get'>;
}
declare module 'ipfs-api/src/config/index.js' {
  declare module.exports: $Exports<'ipfs-api/src/config/index'>;
}
declare module 'ipfs-api/src/config/replace.js' {
  declare module.exports: $Exports<'ipfs-api/src/config/replace'>;
}
declare module 'ipfs-api/src/config/set.js' {
  declare module.exports: $Exports<'ipfs-api/src/config/set'>;
}
declare module 'ipfs-api/src/dht/findpeer.js' {
  declare module.exports: $Exports<'ipfs-api/src/dht/findpeer'>;
}
declare module 'ipfs-api/src/dht/findprovs.js' {
  declare module.exports: $Exports<'ipfs-api/src/dht/findprovs'>;
}
declare module 'ipfs-api/src/dht/get.js' {
  declare module.exports: $Exports<'ipfs-api/src/dht/get'>;
}
declare module 'ipfs-api/src/dht/index.js' {
  declare module.exports: $Exports<'ipfs-api/src/dht/index'>;
}
declare module 'ipfs-api/src/dht/provide.js' {
  declare module.exports: $Exports<'ipfs-api/src/dht/provide'>;
}
declare module 'ipfs-api/src/dht/put.js' {
  declare module.exports: $Exports<'ipfs-api/src/dht/put'>;
}
declare module 'ipfs-api/src/dht/query.js' {
  declare module.exports: $Exports<'ipfs-api/src/dht/query'>;
}
declare module 'ipfs-api/src/diag/cmds.js' {
  declare module.exports: $Exports<'ipfs-api/src/diag/cmds'>;
}
declare module 'ipfs-api/src/diag/index.js' {
  declare module.exports: $Exports<'ipfs-api/src/diag/index'>;
}
declare module 'ipfs-api/src/diag/net.js' {
  declare module.exports: $Exports<'ipfs-api/src/diag/net'>;
}
declare module 'ipfs-api/src/diag/sys.js' {
  declare module.exports: $Exports<'ipfs-api/src/diag/sys'>;
}
declare module 'ipfs-api/src/dns.js' {
  declare module.exports: $Exports<'ipfs-api/src/dns'>;
}
declare module 'ipfs-api/src/files/add-pull-stream.js' {
  declare module.exports: $Exports<'ipfs-api/src/files/add-pull-stream'>;
}
declare module 'ipfs-api/src/files/add-readable-stream.js' {
  declare module.exports: $Exports<'ipfs-api/src/files/add-readable-stream'>;
}
declare module 'ipfs-api/src/files/add.js' {
  declare module.exports: $Exports<'ipfs-api/src/files/add'>;
}
declare module 'ipfs-api/src/files/cat-pull-stream.js' {
  declare module.exports: $Exports<'ipfs-api/src/files/cat-pull-stream'>;
}
declare module 'ipfs-api/src/files/cat-readable-stream.js' {
  declare module.exports: $Exports<'ipfs-api/src/files/cat-readable-stream'>;
}
declare module 'ipfs-api/src/files/cat.js' {
  declare module.exports: $Exports<'ipfs-api/src/files/cat'>;
}
declare module 'ipfs-api/src/files/cp.js' {
  declare module.exports: $Exports<'ipfs-api/src/files/cp'>;
}
declare module 'ipfs-api/src/files/flush.js' {
  declare module.exports: $Exports<'ipfs-api/src/files/flush'>;
}
declare module 'ipfs-api/src/files/get-pull-stream.js' {
  declare module.exports: $Exports<'ipfs-api/src/files/get-pull-stream'>;
}
declare module 'ipfs-api/src/files/get-readable-stream.js' {
  declare module.exports: $Exports<'ipfs-api/src/files/get-readable-stream'>;
}
declare module 'ipfs-api/src/files/get.js' {
  declare module.exports: $Exports<'ipfs-api/src/files/get'>;
}
declare module 'ipfs-api/src/files/index.js' {
  declare module.exports: $Exports<'ipfs-api/src/files/index'>;
}
declare module 'ipfs-api/src/files/ls.js' {
  declare module.exports: $Exports<'ipfs-api/src/files/ls'>;
}
declare module 'ipfs-api/src/files/mkdir.js' {
  declare module.exports: $Exports<'ipfs-api/src/files/mkdir'>;
}
declare module 'ipfs-api/src/files/mv.js' {
  declare module.exports: $Exports<'ipfs-api/src/files/mv'>;
}
declare module 'ipfs-api/src/files/read.js' {
  declare module.exports: $Exports<'ipfs-api/src/files/read'>;
}
declare module 'ipfs-api/src/files/rm.js' {
  declare module.exports: $Exports<'ipfs-api/src/files/rm'>;
}
declare module 'ipfs-api/src/files/stat.js' {
  declare module.exports: $Exports<'ipfs-api/src/files/stat'>;
}
declare module 'ipfs-api/src/files/write.js' {
  declare module.exports: $Exports<'ipfs-api/src/files/write'>;
}
declare module 'ipfs-api/src/get.js' {
  declare module.exports: $Exports<'ipfs-api/src/get'>;
}
declare module 'ipfs-api/src/id.js' {
  declare module.exports: $Exports<'ipfs-api/src/id'>;
}
declare module 'ipfs-api/src/index.js' {
  declare module.exports: $Exports<'ipfs-api/src/index'>;
}
declare module 'ipfs-api/src/key/export.js' {
  declare module.exports: $Exports<'ipfs-api/src/key/export'>;
}
declare module 'ipfs-api/src/key/gen.js' {
  declare module.exports: $Exports<'ipfs-api/src/key/gen'>;
}
declare module 'ipfs-api/src/key/import.js' {
  declare module.exports: $Exports<'ipfs-api/src/key/import'>;
}
declare module 'ipfs-api/src/key/index.js' {
  declare module.exports: $Exports<'ipfs-api/src/key/index'>;
}
declare module 'ipfs-api/src/key/list.js' {
  declare module.exports: $Exports<'ipfs-api/src/key/list'>;
}
declare module 'ipfs-api/src/key/rename.js' {
  declare module.exports: $Exports<'ipfs-api/src/key/rename'>;
}
declare module 'ipfs-api/src/key/rm.js' {
  declare module.exports: $Exports<'ipfs-api/src/key/rm'>;
}
declare module 'ipfs-api/src/log/index.js' {
  declare module.exports: $Exports<'ipfs-api/src/log/index'>;
}
declare module 'ipfs-api/src/log/level.js' {
  declare module.exports: $Exports<'ipfs-api/src/log/level'>;
}
declare module 'ipfs-api/src/log/ls.js' {
  declare module.exports: $Exports<'ipfs-api/src/log/ls'>;
}
declare module 'ipfs-api/src/log/tail.js' {
  declare module.exports: $Exports<'ipfs-api/src/log/tail'>;
}
declare module 'ipfs-api/src/ls-pull-stream.js' {
  declare module.exports: $Exports<'ipfs-api/src/ls-pull-stream'>;
}
declare module 'ipfs-api/src/ls-readable-stream.js' {
  declare module.exports: $Exports<'ipfs-api/src/ls-readable-stream'>;
}
declare module 'ipfs-api/src/ls.js' {
  declare module.exports: $Exports<'ipfs-api/src/ls'>;
}
declare module 'ipfs-api/src/mount.js' {
  declare module.exports: $Exports<'ipfs-api/src/mount'>;
}
declare module 'ipfs-api/src/name/index.js' {
  declare module.exports: $Exports<'ipfs-api/src/name/index'>;
}
declare module 'ipfs-api/src/name/publish.js' {
  declare module.exports: $Exports<'ipfs-api/src/name/publish'>;
}
declare module 'ipfs-api/src/name/resolve.js' {
  declare module.exports: $Exports<'ipfs-api/src/name/resolve'>;
}
declare module 'ipfs-api/src/object/addLink.js' {
  declare module.exports: $Exports<'ipfs-api/src/object/addLink'>;
}
declare module 'ipfs-api/src/object/appendData.js' {
  declare module.exports: $Exports<'ipfs-api/src/object/appendData'>;
}
declare module 'ipfs-api/src/object/data.js' {
  declare module.exports: $Exports<'ipfs-api/src/object/data'>;
}
declare module 'ipfs-api/src/object/get.js' {
  declare module.exports: $Exports<'ipfs-api/src/object/get'>;
}
declare module 'ipfs-api/src/object/index.js' {
  declare module.exports: $Exports<'ipfs-api/src/object/index'>;
}
declare module 'ipfs-api/src/object/links.js' {
  declare module.exports: $Exports<'ipfs-api/src/object/links'>;
}
declare module 'ipfs-api/src/object/new.js' {
  declare module.exports: $Exports<'ipfs-api/src/object/new'>;
}
declare module 'ipfs-api/src/object/put.js' {
  declare module.exports: $Exports<'ipfs-api/src/object/put'>;
}
declare module 'ipfs-api/src/object/rmLink.js' {
  declare module.exports: $Exports<'ipfs-api/src/object/rmLink'>;
}
declare module 'ipfs-api/src/object/setData.js' {
  declare module.exports: $Exports<'ipfs-api/src/object/setData'>;
}
declare module 'ipfs-api/src/object/stat.js' {
  declare module.exports: $Exports<'ipfs-api/src/object/stat'>;
}
declare module 'ipfs-api/src/pin/add.js' {
  declare module.exports: $Exports<'ipfs-api/src/pin/add'>;
}
declare module 'ipfs-api/src/pin/index.js' {
  declare module.exports: $Exports<'ipfs-api/src/pin/index'>;
}
declare module 'ipfs-api/src/pin/ls.js' {
  declare module.exports: $Exports<'ipfs-api/src/pin/ls'>;
}
declare module 'ipfs-api/src/pin/rm.js' {
  declare module.exports: $Exports<'ipfs-api/src/pin/rm'>;
}
declare module 'ipfs-api/src/ping.js' {
  declare module.exports: $Exports<'ipfs-api/src/ping'>;
}
declare module 'ipfs-api/src/pubsub.js' {
  declare module.exports: $Exports<'ipfs-api/src/pubsub'>;
}
declare module 'ipfs-api/src/refs.js' {
  declare module.exports: $Exports<'ipfs-api/src/refs'>;
}
declare module 'ipfs-api/src/repo/gc.js' {
  declare module.exports: $Exports<'ipfs-api/src/repo/gc'>;
}
declare module 'ipfs-api/src/repo/index.js' {
  declare module.exports: $Exports<'ipfs-api/src/repo/index'>;
}
declare module 'ipfs-api/src/repo/stat.js' {
  declare module.exports: $Exports<'ipfs-api/src/repo/stat'>;
}
declare module 'ipfs-api/src/stats/bitswap.js' {
  declare module.exports: $Exports<'ipfs-api/src/stats/bitswap'>;
}
declare module 'ipfs-api/src/stats/bw.js' {
  declare module.exports: $Exports<'ipfs-api/src/stats/bw'>;
}
declare module 'ipfs-api/src/stats/index.js' {
  declare module.exports: $Exports<'ipfs-api/src/stats/index'>;
}
declare module 'ipfs-api/src/stats/repo.js' {
  declare module.exports: $Exports<'ipfs-api/src/stats/repo'>;
}
declare module 'ipfs-api/src/swarm/addrs.js' {
  declare module.exports: $Exports<'ipfs-api/src/swarm/addrs'>;
}
declare module 'ipfs-api/src/swarm/connect.js' {
  declare module.exports: $Exports<'ipfs-api/src/swarm/connect'>;
}
declare module 'ipfs-api/src/swarm/disconnect.js' {
  declare module.exports: $Exports<'ipfs-api/src/swarm/disconnect'>;
}
declare module 'ipfs-api/src/swarm/index.js' {
  declare module.exports: $Exports<'ipfs-api/src/swarm/index'>;
}
declare module 'ipfs-api/src/swarm/localAddrs.js' {
  declare module.exports: $Exports<'ipfs-api/src/swarm/localAddrs'>;
}
declare module 'ipfs-api/src/swarm/peers.js' {
  declare module.exports: $Exports<'ipfs-api/src/swarm/peers'>;
}
declare module 'ipfs-api/src/update.js' {
  declare module.exports: $Exports<'ipfs-api/src/update'>;
}
declare module 'ipfs-api/src/util/fs-add.js' {
  declare module.exports: $Exports<'ipfs-api/src/util/fs-add'>;
}
declare module 'ipfs-api/src/util/url-add.js' {
  declare module.exports: $Exports<'ipfs-api/src/util/url-add'>;
}
declare module 'ipfs-api/src/utils/clean-cid.js' {
  declare module.exports: $Exports<'ipfs-api/src/utils/clean-cid'>;
}
declare module 'ipfs-api/src/utils/clean-multihash.js' {
  declare module.exports: $Exports<'ipfs-api/src/utils/clean-multihash'>;
}
declare module 'ipfs-api/src/utils/converter.js' {
  declare module.exports: $Exports<'ipfs-api/src/utils/converter'>;
}
declare module 'ipfs-api/src/utils/default-config.js' {
  declare module.exports: $Exports<'ipfs-api/src/utils/default-config'>;
}
declare module 'ipfs-api/src/utils/load-commands.js' {
  declare module.exports: $Exports<'ipfs-api/src/utils/load-commands'>;
}
declare module 'ipfs-api/src/utils/module-config.js' {
  declare module.exports: $Exports<'ipfs-api/src/utils/module-config'>;
}
declare module 'ipfs-api/src/utils/multipart.js' {
  declare module.exports: $Exports<'ipfs-api/src/utils/multipart'>;
}
declare module 'ipfs-api/src/utils/prepare-file.js' {
  declare module.exports: $Exports<'ipfs-api/src/utils/prepare-file'>;
}
declare module 'ipfs-api/src/utils/progress-stream.js' {
  declare module.exports: $Exports<'ipfs-api/src/utils/progress-stream'>;
}
declare module 'ipfs-api/src/utils/pubsub-message-stream.js' {
  declare module.exports: $Exports<'ipfs-api/src/utils/pubsub-message-stream'>;
}
declare module 'ipfs-api/src/utils/pubsub-message-utils.js' {
  declare module.exports: $Exports<'ipfs-api/src/utils/pubsub-message-utils'>;
}
declare module 'ipfs-api/src/utils/request.js' {
  declare module.exports: $Exports<'ipfs-api/src/utils/request'>;
}
declare module 'ipfs-api/src/utils/send-files-stream.js' {
  declare module.exports: $Exports<'ipfs-api/src/utils/send-files-stream'>;
}
declare module 'ipfs-api/src/utils/send-one-file-multiple-results.js' {
  declare module.exports: $Exports<'ipfs-api/src/utils/send-one-file-multiple-results'>;
}
declare module 'ipfs-api/src/utils/send-one-file.js' {
  declare module.exports: $Exports<'ipfs-api/src/utils/send-one-file'>;
}
declare module 'ipfs-api/src/utils/send-request.js' {
  declare module.exports: $Exports<'ipfs-api/src/utils/send-request'>;
}
declare module 'ipfs-api/src/utils/stream-to-json-value.js' {
  declare module.exports: $Exports<'ipfs-api/src/utils/stream-to-json-value'>;
}
declare module 'ipfs-api/src/utils/stream-to-value.js' {
  declare module.exports: $Exports<'ipfs-api/src/utils/stream-to-value'>;
}
declare module 'ipfs-api/src/utils/stringlist-to-array.js' {
  declare module.exports: $Exports<'ipfs-api/src/utils/stringlist-to-array'>;
}
declare module 'ipfs-api/src/utils/tar-stream-to-objects.js' {
  declare module.exports: $Exports<'ipfs-api/src/utils/tar-stream-to-objects'>;
}
declare module 'ipfs-api/src/version.js' {
  declare module.exports: $Exports<'ipfs-api/src/version'>;
}
