// flow-typed signature: 5bcbfa0efe13645f571c5c0cbbfdd740
// flow-typed version: <<STUB>>/ipfs-http-client_v^56.0.0/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ipfs-http-client'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ipfs-http-client' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ipfs-http-client/cjs/src/add-all' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/add' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/bitswap' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/bitswap/stat' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/bitswap/unwant' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/bitswap/wantlist-for-peer' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/bitswap/wantlist' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/block/get' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/block' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/block/put' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/block/rm' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/block/stat' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/bootstrap/add' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/bootstrap/clear' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/bootstrap' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/bootstrap/list' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/bootstrap/reset' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/bootstrap/rm' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/cat' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/commands' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/config/get-all' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/config/get' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/config' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/config/profiles/apply' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/config/profiles' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/config/profiles/list' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/config/replace' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/config/set' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/dag/export' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/dag/get' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/dag/import' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/dag' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/dag/put' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/dag/resolve' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/dht/find-peer' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/dht/find-provs' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/dht/get' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/dht' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/dht/map-event' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/dht/provide' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/dht/put' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/dht/query' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/dht/response-types' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/diag/cmds' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/diag' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/diag/net' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/diag/sys' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/dns' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/files/chmod' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/files/cp' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/files/flush' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/files' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/files/ls' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/files/mkdir' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/files/mv' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/files/read' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/files/rm' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/files/stat' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/files/touch' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/files/write' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/get-endpoint-config' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/get' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/id' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/is-online' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/key/export' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/key/gen' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/key/import' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/key' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/key/info' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/key/list' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/key/rename' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/key/rm' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/lib/abort-signal' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/lib/configure' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/lib/core' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/lib/http-rpc-wire-format' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/lib/mode-to-string' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/lib/object-to-camel-with-metadata' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/lib/object-to-camel' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/lib/parse-mtime' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/lib/resolve' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/lib/to-url-search-params' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/log' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/log/level' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/log/ls' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/log/tail' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/ls' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/mount' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/name' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/name/publish' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/name/pubsub/cancel' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/name/pubsub' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/name/pubsub/state' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/name/pubsub/subs' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/name/resolve' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/object/data' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/object/get' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/object' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/object/links' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/object/new' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/object/patch/add-link' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/object/patch/append-data' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/object/patch' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/object/patch/rm-link' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/object/patch/set-data' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/object/put' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/object/stat' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/pin/add-all' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/pin/add' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/pin' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/pin/ls' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/pin/remote/add' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/pin/remote' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/pin/remote/ls' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/pin/remote/rm-all' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/pin/remote/rm' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/pin/remote/service/add' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/pin/remote/service' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/pin/remote/service/ls' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/pin/remote/service/rm' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/pin/remote/service/utils' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/pin/remote/utils' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/pin/rm-all' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/pin/rm' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/ping' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/pubsub' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/pubsub/ls' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/pubsub/peers' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/pubsub/publish' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/pubsub/subscribe' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/pubsub/subscription-tracker' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/pubsub/unsubscribe' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/refs' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/refs/local' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/repo/gc' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/repo' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/repo/stat' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/repo/version' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/resolve' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/start' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/stats/bw' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/stats' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/stop' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/swarm/addrs' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/swarm/connect' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/swarm/disconnect' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/swarm' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/swarm/local-addrs' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/swarm/peers' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/cjs/src/version' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/add-all' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/add' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/bitswap' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/bitswap/stat' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/bitswap/unwant' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/bitswap/wantlist-for-peer' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/bitswap/wantlist' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/block/get' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/block' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/block/put' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/block/rm' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/block/stat' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/bootstrap/add' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/bootstrap/clear' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/bootstrap' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/bootstrap/list' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/bootstrap/reset' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/bootstrap/rm' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/cat' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/commands' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/config/get-all' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/config/get' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/config' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/config/profiles/apply' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/config/profiles' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/config/profiles/list' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/config/replace' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/config/set' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/dag/export' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/dag/get' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/dag/import' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/dag' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/dag/put' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/dag/resolve' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/dht/find-peer' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/dht/find-provs' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/dht/get' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/dht' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/dht/map-event' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/dht/provide' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/dht/put' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/dht/query' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/dht/response-types' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/diag/cmds' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/diag' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/diag/net' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/diag/sys' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/dns' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/files/chmod' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/files/cp' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/files/flush' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/files' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/files/ls' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/files/mkdir' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/files/mv' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/files/read' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/files/rm' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/files/stat' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/files/touch' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/files/write' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/get-endpoint-config' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/get' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/id' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/is-online' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/key/export' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/key/gen' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/key/import' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/key' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/key/info' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/key/list' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/key/rename' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/key/rm' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/lib/abort-signal' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/lib/configure' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/lib/core' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/lib/http-rpc-wire-format' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/lib/mode-to-string' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/lib/object-to-camel-with-metadata' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/lib/object-to-camel' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/lib/parse-mtime' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/lib/resolve' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/lib/to-url-search-params' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/log' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/log/level' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/log/ls' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/log/tail' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/ls' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/mount' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/name' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/name/publish' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/name/pubsub/cancel' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/name/pubsub' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/name/pubsub/state' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/name/pubsub/subs' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/name/resolve' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/object/data' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/object/get' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/object' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/object/links' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/object/new' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/object/patch/add-link' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/object/patch/append-data' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/object/patch' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/object/patch/rm-link' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/object/patch/set-data' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/object/put' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/object/stat' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/pin/add-all' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/pin/add' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/pin' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/pin/ls' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/pin/remote/add' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/pin/remote' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/pin/remote/ls' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/pin/remote/rm-all' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/pin/remote/rm' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/pin/remote/service/add' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/pin/remote/service' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/pin/remote/service/ls' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/pin/remote/service/rm' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/pin/remote/service/utils' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/pin/remote/utils' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/pin/rm-all' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/pin/rm' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/ping' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/pubsub' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/pubsub/ls' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/pubsub/peers' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/pubsub/publish' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/pubsub/subscribe' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/pubsub/subscription-tracker' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/pubsub/unsubscribe' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/refs' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/refs/local' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/repo/gc' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/repo' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/repo/stat' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/repo/version' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/resolve' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/start' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/stats/bw' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/stats' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/stop' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/swarm/addrs' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/swarm/connect' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/swarm/disconnect' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/swarm' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/swarm/local-addrs' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/swarm/peers' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/esm/src/version' {
  declare module.exports: any;
}

declare module 'ipfs-http-client/index.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ipfs-http-client/cjs/src/add-all.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/add-all'>;
}
declare module 'ipfs-http-client/cjs/src/add.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/add'>;
}
declare module 'ipfs-http-client/cjs/src/bitswap/index' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/bitswap'>;
}
declare module 'ipfs-http-client/cjs/src/bitswap/index.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/bitswap'>;
}
declare module 'ipfs-http-client/cjs/src/bitswap/stat.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/bitswap/stat'>;
}
declare module 'ipfs-http-client/cjs/src/bitswap/unwant.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/bitswap/unwant'>;
}
declare module 'ipfs-http-client/cjs/src/bitswap/wantlist-for-peer.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/bitswap/wantlist-for-peer'>;
}
declare module 'ipfs-http-client/cjs/src/bitswap/wantlist.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/bitswap/wantlist'>;
}
declare module 'ipfs-http-client/cjs/src/block/get.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/block/get'>;
}
declare module 'ipfs-http-client/cjs/src/block/index' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/block'>;
}
declare module 'ipfs-http-client/cjs/src/block/index.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/block'>;
}
declare module 'ipfs-http-client/cjs/src/block/put.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/block/put'>;
}
declare module 'ipfs-http-client/cjs/src/block/rm.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/block/rm'>;
}
declare module 'ipfs-http-client/cjs/src/block/stat.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/block/stat'>;
}
declare module 'ipfs-http-client/cjs/src/bootstrap/add.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/bootstrap/add'>;
}
declare module 'ipfs-http-client/cjs/src/bootstrap/clear.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/bootstrap/clear'>;
}
declare module 'ipfs-http-client/cjs/src/bootstrap/index' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/bootstrap'>;
}
declare module 'ipfs-http-client/cjs/src/bootstrap/index.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/bootstrap'>;
}
declare module 'ipfs-http-client/cjs/src/bootstrap/list.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/bootstrap/list'>;
}
declare module 'ipfs-http-client/cjs/src/bootstrap/reset.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/bootstrap/reset'>;
}
declare module 'ipfs-http-client/cjs/src/bootstrap/rm.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/bootstrap/rm'>;
}
declare module 'ipfs-http-client/cjs/src/cat.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/cat'>;
}
declare module 'ipfs-http-client/cjs/src/commands.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/commands'>;
}
declare module 'ipfs-http-client/cjs/src/config/get-all.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/config/get-all'>;
}
declare module 'ipfs-http-client/cjs/src/config/get.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/config/get'>;
}
declare module 'ipfs-http-client/cjs/src/config/index' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/config'>;
}
declare module 'ipfs-http-client/cjs/src/config/index.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/config'>;
}
declare module 'ipfs-http-client/cjs/src/config/profiles/apply.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/config/profiles/apply'>;
}
declare module 'ipfs-http-client/cjs/src/config/profiles/index' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/config/profiles'>;
}
declare module 'ipfs-http-client/cjs/src/config/profiles/index.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/config/profiles'>;
}
declare module 'ipfs-http-client/cjs/src/config/profiles/list.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/config/profiles/list'>;
}
declare module 'ipfs-http-client/cjs/src/config/replace.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/config/replace'>;
}
declare module 'ipfs-http-client/cjs/src/config/set.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/config/set'>;
}
declare module 'ipfs-http-client/cjs/src/dag/export.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/dag/export'>;
}
declare module 'ipfs-http-client/cjs/src/dag/get.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/dag/get'>;
}
declare module 'ipfs-http-client/cjs/src/dag/import.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/dag/import'>;
}
declare module 'ipfs-http-client/cjs/src/dag/index' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/dag'>;
}
declare module 'ipfs-http-client/cjs/src/dag/index.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/dag'>;
}
declare module 'ipfs-http-client/cjs/src/dag/put.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/dag/put'>;
}
declare module 'ipfs-http-client/cjs/src/dag/resolve.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/dag/resolve'>;
}
declare module 'ipfs-http-client/cjs/src/dht/find-peer.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/dht/find-peer'>;
}
declare module 'ipfs-http-client/cjs/src/dht/find-provs.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/dht/find-provs'>;
}
declare module 'ipfs-http-client/cjs/src/dht/get.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/dht/get'>;
}
declare module 'ipfs-http-client/cjs/src/dht/index' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/dht'>;
}
declare module 'ipfs-http-client/cjs/src/dht/index.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/dht'>;
}
declare module 'ipfs-http-client/cjs/src/dht/map-event.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/dht/map-event'>;
}
declare module 'ipfs-http-client/cjs/src/dht/provide.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/dht/provide'>;
}
declare module 'ipfs-http-client/cjs/src/dht/put.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/dht/put'>;
}
declare module 'ipfs-http-client/cjs/src/dht/query.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/dht/query'>;
}
declare module 'ipfs-http-client/cjs/src/dht/response-types.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/dht/response-types'>;
}
declare module 'ipfs-http-client/cjs/src/diag/cmds.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/diag/cmds'>;
}
declare module 'ipfs-http-client/cjs/src/diag/index' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/diag'>;
}
declare module 'ipfs-http-client/cjs/src/diag/index.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/diag'>;
}
declare module 'ipfs-http-client/cjs/src/diag/net.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/diag/net'>;
}
declare module 'ipfs-http-client/cjs/src/diag/sys.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/diag/sys'>;
}
declare module 'ipfs-http-client/cjs/src/dns.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/dns'>;
}
declare module 'ipfs-http-client/cjs/src/files/chmod.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/files/chmod'>;
}
declare module 'ipfs-http-client/cjs/src/files/cp.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/files/cp'>;
}
declare module 'ipfs-http-client/cjs/src/files/flush.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/files/flush'>;
}
declare module 'ipfs-http-client/cjs/src/files/index' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/files'>;
}
declare module 'ipfs-http-client/cjs/src/files/index.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/files'>;
}
declare module 'ipfs-http-client/cjs/src/files/ls.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/files/ls'>;
}
declare module 'ipfs-http-client/cjs/src/files/mkdir.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/files/mkdir'>;
}
declare module 'ipfs-http-client/cjs/src/files/mv.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/files/mv'>;
}
declare module 'ipfs-http-client/cjs/src/files/read.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/files/read'>;
}
declare module 'ipfs-http-client/cjs/src/files/rm.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/files/rm'>;
}
declare module 'ipfs-http-client/cjs/src/files/stat.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/files/stat'>;
}
declare module 'ipfs-http-client/cjs/src/files/touch.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/files/touch'>;
}
declare module 'ipfs-http-client/cjs/src/files/write.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/files/write'>;
}
declare module 'ipfs-http-client/cjs/src/get-endpoint-config.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/get-endpoint-config'>;
}
declare module 'ipfs-http-client/cjs/src/get.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/get'>;
}
declare module 'ipfs-http-client/cjs/src/id.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/id'>;
}
declare module 'ipfs-http-client/cjs/src/index' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src'>;
}
declare module 'ipfs-http-client/cjs/src/index.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src'>;
}
declare module 'ipfs-http-client/cjs/src/is-online.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/is-online'>;
}
declare module 'ipfs-http-client/cjs/src/key/export.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/key/export'>;
}
declare module 'ipfs-http-client/cjs/src/key/gen.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/key/gen'>;
}
declare module 'ipfs-http-client/cjs/src/key/import.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/key/import'>;
}
declare module 'ipfs-http-client/cjs/src/key/index' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/key'>;
}
declare module 'ipfs-http-client/cjs/src/key/index.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/key'>;
}
declare module 'ipfs-http-client/cjs/src/key/info.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/key/info'>;
}
declare module 'ipfs-http-client/cjs/src/key/list.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/key/list'>;
}
declare module 'ipfs-http-client/cjs/src/key/rename.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/key/rename'>;
}
declare module 'ipfs-http-client/cjs/src/key/rm.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/key/rm'>;
}
declare module 'ipfs-http-client/cjs/src/lib/abort-signal.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/lib/abort-signal'>;
}
declare module 'ipfs-http-client/cjs/src/lib/configure.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/lib/configure'>;
}
declare module 'ipfs-http-client/cjs/src/lib/core.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/lib/core'>;
}
declare module 'ipfs-http-client/cjs/src/lib/http-rpc-wire-format.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/lib/http-rpc-wire-format'>;
}
declare module 'ipfs-http-client/cjs/src/lib/mode-to-string.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/lib/mode-to-string'>;
}
declare module 'ipfs-http-client/cjs/src/lib/object-to-camel-with-metadata.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/lib/object-to-camel-with-metadata'>;
}
declare module 'ipfs-http-client/cjs/src/lib/object-to-camel.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/lib/object-to-camel'>;
}
declare module 'ipfs-http-client/cjs/src/lib/parse-mtime.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/lib/parse-mtime'>;
}
declare module 'ipfs-http-client/cjs/src/lib/resolve.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/lib/resolve'>;
}
declare module 'ipfs-http-client/cjs/src/lib/to-url-search-params.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/lib/to-url-search-params'>;
}
declare module 'ipfs-http-client/cjs/src/log/index' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/log'>;
}
declare module 'ipfs-http-client/cjs/src/log/index.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/log'>;
}
declare module 'ipfs-http-client/cjs/src/log/level.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/log/level'>;
}
declare module 'ipfs-http-client/cjs/src/log/ls.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/log/ls'>;
}
declare module 'ipfs-http-client/cjs/src/log/tail.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/log/tail'>;
}
declare module 'ipfs-http-client/cjs/src/ls.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/ls'>;
}
declare module 'ipfs-http-client/cjs/src/mount.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/mount'>;
}
declare module 'ipfs-http-client/cjs/src/name/index' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/name'>;
}
declare module 'ipfs-http-client/cjs/src/name/index.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/name'>;
}
declare module 'ipfs-http-client/cjs/src/name/publish.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/name/publish'>;
}
declare module 'ipfs-http-client/cjs/src/name/pubsub/cancel.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/name/pubsub/cancel'>;
}
declare module 'ipfs-http-client/cjs/src/name/pubsub/index' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/name/pubsub'>;
}
declare module 'ipfs-http-client/cjs/src/name/pubsub/index.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/name/pubsub'>;
}
declare module 'ipfs-http-client/cjs/src/name/pubsub/state.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/name/pubsub/state'>;
}
declare module 'ipfs-http-client/cjs/src/name/pubsub/subs.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/name/pubsub/subs'>;
}
declare module 'ipfs-http-client/cjs/src/name/resolve.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/name/resolve'>;
}
declare module 'ipfs-http-client/cjs/src/object/data.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/object/data'>;
}
declare module 'ipfs-http-client/cjs/src/object/get.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/object/get'>;
}
declare module 'ipfs-http-client/cjs/src/object/index' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/object'>;
}
declare module 'ipfs-http-client/cjs/src/object/index.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/object'>;
}
declare module 'ipfs-http-client/cjs/src/object/links.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/object/links'>;
}
declare module 'ipfs-http-client/cjs/src/object/new.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/object/new'>;
}
declare module 'ipfs-http-client/cjs/src/object/patch/add-link.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/object/patch/add-link'>;
}
declare module 'ipfs-http-client/cjs/src/object/patch/append-data.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/object/patch/append-data'>;
}
declare module 'ipfs-http-client/cjs/src/object/patch/index' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/object/patch'>;
}
declare module 'ipfs-http-client/cjs/src/object/patch/index.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/object/patch'>;
}
declare module 'ipfs-http-client/cjs/src/object/patch/rm-link.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/object/patch/rm-link'>;
}
declare module 'ipfs-http-client/cjs/src/object/patch/set-data.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/object/patch/set-data'>;
}
declare module 'ipfs-http-client/cjs/src/object/put.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/object/put'>;
}
declare module 'ipfs-http-client/cjs/src/object/stat.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/object/stat'>;
}
declare module 'ipfs-http-client/cjs/src/pin/add-all.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/pin/add-all'>;
}
declare module 'ipfs-http-client/cjs/src/pin/add.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/pin/add'>;
}
declare module 'ipfs-http-client/cjs/src/pin/index' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/pin'>;
}
declare module 'ipfs-http-client/cjs/src/pin/index.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/pin'>;
}
declare module 'ipfs-http-client/cjs/src/pin/ls.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/pin/ls'>;
}
declare module 'ipfs-http-client/cjs/src/pin/remote/add.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/pin/remote/add'>;
}
declare module 'ipfs-http-client/cjs/src/pin/remote/index' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/pin/remote'>;
}
declare module 'ipfs-http-client/cjs/src/pin/remote/index.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/pin/remote'>;
}
declare module 'ipfs-http-client/cjs/src/pin/remote/ls.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/pin/remote/ls'>;
}
declare module 'ipfs-http-client/cjs/src/pin/remote/rm-all.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/pin/remote/rm-all'>;
}
declare module 'ipfs-http-client/cjs/src/pin/remote/rm.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/pin/remote/rm'>;
}
declare module 'ipfs-http-client/cjs/src/pin/remote/service/add.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/pin/remote/service/add'>;
}
declare module 'ipfs-http-client/cjs/src/pin/remote/service/index' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/pin/remote/service'>;
}
declare module 'ipfs-http-client/cjs/src/pin/remote/service/index.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/pin/remote/service'>;
}
declare module 'ipfs-http-client/cjs/src/pin/remote/service/ls.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/pin/remote/service/ls'>;
}
declare module 'ipfs-http-client/cjs/src/pin/remote/service/rm.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/pin/remote/service/rm'>;
}
declare module 'ipfs-http-client/cjs/src/pin/remote/service/utils.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/pin/remote/service/utils'>;
}
declare module 'ipfs-http-client/cjs/src/pin/remote/utils.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/pin/remote/utils'>;
}
declare module 'ipfs-http-client/cjs/src/pin/rm-all.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/pin/rm-all'>;
}
declare module 'ipfs-http-client/cjs/src/pin/rm.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/pin/rm'>;
}
declare module 'ipfs-http-client/cjs/src/ping.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/ping'>;
}
declare module 'ipfs-http-client/cjs/src/pubsub/index' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/pubsub'>;
}
declare module 'ipfs-http-client/cjs/src/pubsub/index.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/pubsub'>;
}
declare module 'ipfs-http-client/cjs/src/pubsub/ls.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/pubsub/ls'>;
}
declare module 'ipfs-http-client/cjs/src/pubsub/peers.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/pubsub/peers'>;
}
declare module 'ipfs-http-client/cjs/src/pubsub/publish.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/pubsub/publish'>;
}
declare module 'ipfs-http-client/cjs/src/pubsub/subscribe.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/pubsub/subscribe'>;
}
declare module 'ipfs-http-client/cjs/src/pubsub/subscription-tracker.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/pubsub/subscription-tracker'>;
}
declare module 'ipfs-http-client/cjs/src/pubsub/unsubscribe.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/pubsub/unsubscribe'>;
}
declare module 'ipfs-http-client/cjs/src/refs/index' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/refs'>;
}
declare module 'ipfs-http-client/cjs/src/refs/index.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/refs'>;
}
declare module 'ipfs-http-client/cjs/src/refs/local.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/refs/local'>;
}
declare module 'ipfs-http-client/cjs/src/repo/gc.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/repo/gc'>;
}
declare module 'ipfs-http-client/cjs/src/repo/index' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/repo'>;
}
declare module 'ipfs-http-client/cjs/src/repo/index.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/repo'>;
}
declare module 'ipfs-http-client/cjs/src/repo/stat.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/repo/stat'>;
}
declare module 'ipfs-http-client/cjs/src/repo/version.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/repo/version'>;
}
declare module 'ipfs-http-client/cjs/src/resolve.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/resolve'>;
}
declare module 'ipfs-http-client/cjs/src/start.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/start'>;
}
declare module 'ipfs-http-client/cjs/src/stats/bw.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/stats/bw'>;
}
declare module 'ipfs-http-client/cjs/src/stats/index' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/stats'>;
}
declare module 'ipfs-http-client/cjs/src/stats/index.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/stats'>;
}
declare module 'ipfs-http-client/cjs/src/stop.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/stop'>;
}
declare module 'ipfs-http-client/cjs/src/swarm/addrs.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/swarm/addrs'>;
}
declare module 'ipfs-http-client/cjs/src/swarm/connect.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/swarm/connect'>;
}
declare module 'ipfs-http-client/cjs/src/swarm/disconnect.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/swarm/disconnect'>;
}
declare module 'ipfs-http-client/cjs/src/swarm/index' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/swarm'>;
}
declare module 'ipfs-http-client/cjs/src/swarm/index.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/swarm'>;
}
declare module 'ipfs-http-client/cjs/src/swarm/local-addrs.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/swarm/local-addrs'>;
}
declare module 'ipfs-http-client/cjs/src/swarm/peers.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/swarm/peers'>;
}
declare module 'ipfs-http-client/cjs/src/version.js' {
  declare module.exports: $Exports<'ipfs-http-client/cjs/src/version'>;
}
declare module 'ipfs-http-client/esm/src/add-all.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/add-all'>;
}
declare module 'ipfs-http-client/esm/src/add.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/add'>;
}
declare module 'ipfs-http-client/esm/src/bitswap/index' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/bitswap'>;
}
declare module 'ipfs-http-client/esm/src/bitswap/index.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/bitswap'>;
}
declare module 'ipfs-http-client/esm/src/bitswap/stat.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/bitswap/stat'>;
}
declare module 'ipfs-http-client/esm/src/bitswap/unwant.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/bitswap/unwant'>;
}
declare module 'ipfs-http-client/esm/src/bitswap/wantlist-for-peer.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/bitswap/wantlist-for-peer'>;
}
declare module 'ipfs-http-client/esm/src/bitswap/wantlist.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/bitswap/wantlist'>;
}
declare module 'ipfs-http-client/esm/src/block/get.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/block/get'>;
}
declare module 'ipfs-http-client/esm/src/block/index' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/block'>;
}
declare module 'ipfs-http-client/esm/src/block/index.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/block'>;
}
declare module 'ipfs-http-client/esm/src/block/put.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/block/put'>;
}
declare module 'ipfs-http-client/esm/src/block/rm.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/block/rm'>;
}
declare module 'ipfs-http-client/esm/src/block/stat.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/block/stat'>;
}
declare module 'ipfs-http-client/esm/src/bootstrap/add.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/bootstrap/add'>;
}
declare module 'ipfs-http-client/esm/src/bootstrap/clear.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/bootstrap/clear'>;
}
declare module 'ipfs-http-client/esm/src/bootstrap/index' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/bootstrap'>;
}
declare module 'ipfs-http-client/esm/src/bootstrap/index.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/bootstrap'>;
}
declare module 'ipfs-http-client/esm/src/bootstrap/list.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/bootstrap/list'>;
}
declare module 'ipfs-http-client/esm/src/bootstrap/reset.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/bootstrap/reset'>;
}
declare module 'ipfs-http-client/esm/src/bootstrap/rm.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/bootstrap/rm'>;
}
declare module 'ipfs-http-client/esm/src/cat.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/cat'>;
}
declare module 'ipfs-http-client/esm/src/commands.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/commands'>;
}
declare module 'ipfs-http-client/esm/src/config/get-all.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/config/get-all'>;
}
declare module 'ipfs-http-client/esm/src/config/get.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/config/get'>;
}
declare module 'ipfs-http-client/esm/src/config/index' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/config'>;
}
declare module 'ipfs-http-client/esm/src/config/index.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/config'>;
}
declare module 'ipfs-http-client/esm/src/config/profiles/apply.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/config/profiles/apply'>;
}
declare module 'ipfs-http-client/esm/src/config/profiles/index' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/config/profiles'>;
}
declare module 'ipfs-http-client/esm/src/config/profiles/index.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/config/profiles'>;
}
declare module 'ipfs-http-client/esm/src/config/profiles/list.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/config/profiles/list'>;
}
declare module 'ipfs-http-client/esm/src/config/replace.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/config/replace'>;
}
declare module 'ipfs-http-client/esm/src/config/set.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/config/set'>;
}
declare module 'ipfs-http-client/esm/src/dag/export.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/dag/export'>;
}
declare module 'ipfs-http-client/esm/src/dag/get.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/dag/get'>;
}
declare module 'ipfs-http-client/esm/src/dag/import.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/dag/import'>;
}
declare module 'ipfs-http-client/esm/src/dag/index' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/dag'>;
}
declare module 'ipfs-http-client/esm/src/dag/index.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/dag'>;
}
declare module 'ipfs-http-client/esm/src/dag/put.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/dag/put'>;
}
declare module 'ipfs-http-client/esm/src/dag/resolve.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/dag/resolve'>;
}
declare module 'ipfs-http-client/esm/src/dht/find-peer.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/dht/find-peer'>;
}
declare module 'ipfs-http-client/esm/src/dht/find-provs.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/dht/find-provs'>;
}
declare module 'ipfs-http-client/esm/src/dht/get.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/dht/get'>;
}
declare module 'ipfs-http-client/esm/src/dht/index' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/dht'>;
}
declare module 'ipfs-http-client/esm/src/dht/index.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/dht'>;
}
declare module 'ipfs-http-client/esm/src/dht/map-event.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/dht/map-event'>;
}
declare module 'ipfs-http-client/esm/src/dht/provide.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/dht/provide'>;
}
declare module 'ipfs-http-client/esm/src/dht/put.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/dht/put'>;
}
declare module 'ipfs-http-client/esm/src/dht/query.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/dht/query'>;
}
declare module 'ipfs-http-client/esm/src/dht/response-types.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/dht/response-types'>;
}
declare module 'ipfs-http-client/esm/src/diag/cmds.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/diag/cmds'>;
}
declare module 'ipfs-http-client/esm/src/diag/index' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/diag'>;
}
declare module 'ipfs-http-client/esm/src/diag/index.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/diag'>;
}
declare module 'ipfs-http-client/esm/src/diag/net.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/diag/net'>;
}
declare module 'ipfs-http-client/esm/src/diag/sys.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/diag/sys'>;
}
declare module 'ipfs-http-client/esm/src/dns.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/dns'>;
}
declare module 'ipfs-http-client/esm/src/files/chmod.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/files/chmod'>;
}
declare module 'ipfs-http-client/esm/src/files/cp.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/files/cp'>;
}
declare module 'ipfs-http-client/esm/src/files/flush.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/files/flush'>;
}
declare module 'ipfs-http-client/esm/src/files/index' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/files'>;
}
declare module 'ipfs-http-client/esm/src/files/index.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/files'>;
}
declare module 'ipfs-http-client/esm/src/files/ls.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/files/ls'>;
}
declare module 'ipfs-http-client/esm/src/files/mkdir.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/files/mkdir'>;
}
declare module 'ipfs-http-client/esm/src/files/mv.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/files/mv'>;
}
declare module 'ipfs-http-client/esm/src/files/read.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/files/read'>;
}
declare module 'ipfs-http-client/esm/src/files/rm.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/files/rm'>;
}
declare module 'ipfs-http-client/esm/src/files/stat.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/files/stat'>;
}
declare module 'ipfs-http-client/esm/src/files/touch.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/files/touch'>;
}
declare module 'ipfs-http-client/esm/src/files/write.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/files/write'>;
}
declare module 'ipfs-http-client/esm/src/get-endpoint-config.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/get-endpoint-config'>;
}
declare module 'ipfs-http-client/esm/src/get.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/get'>;
}
declare module 'ipfs-http-client/esm/src/id.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/id'>;
}
declare module 'ipfs-http-client/esm/src/index' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src'>;
}
declare module 'ipfs-http-client/esm/src/index.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src'>;
}
declare module 'ipfs-http-client/esm/src/is-online.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/is-online'>;
}
declare module 'ipfs-http-client/esm/src/key/export.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/key/export'>;
}
declare module 'ipfs-http-client/esm/src/key/gen.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/key/gen'>;
}
declare module 'ipfs-http-client/esm/src/key/import.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/key/import'>;
}
declare module 'ipfs-http-client/esm/src/key/index' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/key'>;
}
declare module 'ipfs-http-client/esm/src/key/index.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/key'>;
}
declare module 'ipfs-http-client/esm/src/key/info.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/key/info'>;
}
declare module 'ipfs-http-client/esm/src/key/list.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/key/list'>;
}
declare module 'ipfs-http-client/esm/src/key/rename.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/key/rename'>;
}
declare module 'ipfs-http-client/esm/src/key/rm.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/key/rm'>;
}
declare module 'ipfs-http-client/esm/src/lib/abort-signal.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/lib/abort-signal'>;
}
declare module 'ipfs-http-client/esm/src/lib/configure.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/lib/configure'>;
}
declare module 'ipfs-http-client/esm/src/lib/core.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/lib/core'>;
}
declare module 'ipfs-http-client/esm/src/lib/http-rpc-wire-format.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/lib/http-rpc-wire-format'>;
}
declare module 'ipfs-http-client/esm/src/lib/mode-to-string.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/lib/mode-to-string'>;
}
declare module 'ipfs-http-client/esm/src/lib/object-to-camel-with-metadata.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/lib/object-to-camel-with-metadata'>;
}
declare module 'ipfs-http-client/esm/src/lib/object-to-camel.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/lib/object-to-camel'>;
}
declare module 'ipfs-http-client/esm/src/lib/parse-mtime.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/lib/parse-mtime'>;
}
declare module 'ipfs-http-client/esm/src/lib/resolve.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/lib/resolve'>;
}
declare module 'ipfs-http-client/esm/src/lib/to-url-search-params.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/lib/to-url-search-params'>;
}
declare module 'ipfs-http-client/esm/src/log/index' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/log'>;
}
declare module 'ipfs-http-client/esm/src/log/index.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/log'>;
}
declare module 'ipfs-http-client/esm/src/log/level.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/log/level'>;
}
declare module 'ipfs-http-client/esm/src/log/ls.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/log/ls'>;
}
declare module 'ipfs-http-client/esm/src/log/tail.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/log/tail'>;
}
declare module 'ipfs-http-client/esm/src/ls.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/ls'>;
}
declare module 'ipfs-http-client/esm/src/mount.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/mount'>;
}
declare module 'ipfs-http-client/esm/src/name/index' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/name'>;
}
declare module 'ipfs-http-client/esm/src/name/index.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/name'>;
}
declare module 'ipfs-http-client/esm/src/name/publish.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/name/publish'>;
}
declare module 'ipfs-http-client/esm/src/name/pubsub/cancel.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/name/pubsub/cancel'>;
}
declare module 'ipfs-http-client/esm/src/name/pubsub/index' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/name/pubsub'>;
}
declare module 'ipfs-http-client/esm/src/name/pubsub/index.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/name/pubsub'>;
}
declare module 'ipfs-http-client/esm/src/name/pubsub/state.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/name/pubsub/state'>;
}
declare module 'ipfs-http-client/esm/src/name/pubsub/subs.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/name/pubsub/subs'>;
}
declare module 'ipfs-http-client/esm/src/name/resolve.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/name/resolve'>;
}
declare module 'ipfs-http-client/esm/src/object/data.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/object/data'>;
}
declare module 'ipfs-http-client/esm/src/object/get.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/object/get'>;
}
declare module 'ipfs-http-client/esm/src/object/index' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/object'>;
}
declare module 'ipfs-http-client/esm/src/object/index.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/object'>;
}
declare module 'ipfs-http-client/esm/src/object/links.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/object/links'>;
}
declare module 'ipfs-http-client/esm/src/object/new.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/object/new'>;
}
declare module 'ipfs-http-client/esm/src/object/patch/add-link.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/object/patch/add-link'>;
}
declare module 'ipfs-http-client/esm/src/object/patch/append-data.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/object/patch/append-data'>;
}
declare module 'ipfs-http-client/esm/src/object/patch/index' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/object/patch'>;
}
declare module 'ipfs-http-client/esm/src/object/patch/index.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/object/patch'>;
}
declare module 'ipfs-http-client/esm/src/object/patch/rm-link.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/object/patch/rm-link'>;
}
declare module 'ipfs-http-client/esm/src/object/patch/set-data.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/object/patch/set-data'>;
}
declare module 'ipfs-http-client/esm/src/object/put.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/object/put'>;
}
declare module 'ipfs-http-client/esm/src/object/stat.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/object/stat'>;
}
declare module 'ipfs-http-client/esm/src/pin/add-all.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/pin/add-all'>;
}
declare module 'ipfs-http-client/esm/src/pin/add.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/pin/add'>;
}
declare module 'ipfs-http-client/esm/src/pin/index' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/pin'>;
}
declare module 'ipfs-http-client/esm/src/pin/index.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/pin'>;
}
declare module 'ipfs-http-client/esm/src/pin/ls.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/pin/ls'>;
}
declare module 'ipfs-http-client/esm/src/pin/remote/add.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/pin/remote/add'>;
}
declare module 'ipfs-http-client/esm/src/pin/remote/index' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/pin/remote'>;
}
declare module 'ipfs-http-client/esm/src/pin/remote/index.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/pin/remote'>;
}
declare module 'ipfs-http-client/esm/src/pin/remote/ls.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/pin/remote/ls'>;
}
declare module 'ipfs-http-client/esm/src/pin/remote/rm-all.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/pin/remote/rm-all'>;
}
declare module 'ipfs-http-client/esm/src/pin/remote/rm.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/pin/remote/rm'>;
}
declare module 'ipfs-http-client/esm/src/pin/remote/service/add.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/pin/remote/service/add'>;
}
declare module 'ipfs-http-client/esm/src/pin/remote/service/index' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/pin/remote/service'>;
}
declare module 'ipfs-http-client/esm/src/pin/remote/service/index.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/pin/remote/service'>;
}
declare module 'ipfs-http-client/esm/src/pin/remote/service/ls.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/pin/remote/service/ls'>;
}
declare module 'ipfs-http-client/esm/src/pin/remote/service/rm.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/pin/remote/service/rm'>;
}
declare module 'ipfs-http-client/esm/src/pin/remote/service/utils.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/pin/remote/service/utils'>;
}
declare module 'ipfs-http-client/esm/src/pin/remote/utils.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/pin/remote/utils'>;
}
declare module 'ipfs-http-client/esm/src/pin/rm-all.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/pin/rm-all'>;
}
declare module 'ipfs-http-client/esm/src/pin/rm.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/pin/rm'>;
}
declare module 'ipfs-http-client/esm/src/ping.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/ping'>;
}
declare module 'ipfs-http-client/esm/src/pubsub/index' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/pubsub'>;
}
declare module 'ipfs-http-client/esm/src/pubsub/index.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/pubsub'>;
}
declare module 'ipfs-http-client/esm/src/pubsub/ls.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/pubsub/ls'>;
}
declare module 'ipfs-http-client/esm/src/pubsub/peers.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/pubsub/peers'>;
}
declare module 'ipfs-http-client/esm/src/pubsub/publish.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/pubsub/publish'>;
}
declare module 'ipfs-http-client/esm/src/pubsub/subscribe.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/pubsub/subscribe'>;
}
declare module 'ipfs-http-client/esm/src/pubsub/subscription-tracker.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/pubsub/subscription-tracker'>;
}
declare module 'ipfs-http-client/esm/src/pubsub/unsubscribe.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/pubsub/unsubscribe'>;
}
declare module 'ipfs-http-client/esm/src/refs/index' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/refs'>;
}
declare module 'ipfs-http-client/esm/src/refs/index.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/refs'>;
}
declare module 'ipfs-http-client/esm/src/refs/local.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/refs/local'>;
}
declare module 'ipfs-http-client/esm/src/repo/gc.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/repo/gc'>;
}
declare module 'ipfs-http-client/esm/src/repo/index' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/repo'>;
}
declare module 'ipfs-http-client/esm/src/repo/index.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/repo'>;
}
declare module 'ipfs-http-client/esm/src/repo/stat.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/repo/stat'>;
}
declare module 'ipfs-http-client/esm/src/repo/version.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/repo/version'>;
}
declare module 'ipfs-http-client/esm/src/resolve.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/resolve'>;
}
declare module 'ipfs-http-client/esm/src/start.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/start'>;
}
declare module 'ipfs-http-client/esm/src/stats/bw.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/stats/bw'>;
}
declare module 'ipfs-http-client/esm/src/stats/index' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/stats'>;
}
declare module 'ipfs-http-client/esm/src/stats/index.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/stats'>;
}
declare module 'ipfs-http-client/esm/src/stop.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/stop'>;
}
declare module 'ipfs-http-client/esm/src/swarm/addrs.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/swarm/addrs'>;
}
declare module 'ipfs-http-client/esm/src/swarm/connect.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/swarm/connect'>;
}
declare module 'ipfs-http-client/esm/src/swarm/disconnect.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/swarm/disconnect'>;
}
declare module 'ipfs-http-client/esm/src/swarm/index' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/swarm'>;
}
declare module 'ipfs-http-client/esm/src/swarm/index.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/swarm'>;
}
declare module 'ipfs-http-client/esm/src/swarm/local-addrs.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/swarm/local-addrs'>;
}
declare module 'ipfs-http-client/esm/src/swarm/peers.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/swarm/peers'>;
}
declare module 'ipfs-http-client/esm/src/version.js' {
  declare module.exports: $Exports<'ipfs-http-client/esm/src/version'>;
}
declare module 'ipfs-http-client/index' {
  declare module.exports: $Exports<'ipfs-http-client'>;
}
declare module 'ipfs-http-client/index.js' {
  declare module.exports: $Exports<'ipfs-http-client'>;
}
declare module 'ipfs-http-client/index.min.js' {
  declare module.exports: $Exports<'ipfs-http-client/index.min'>;
}
