// flow-typed signature: 6069647686d59761c1ec78a7bbab4395
// flow-typed version: <<STUB>>/ipfsd-ctl_v^10.0.5/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ipfsd-ctl'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ipfsd-ctl' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ipfsd-ctl/dist/index.min' {
  declare module.exports: any;
}

declare module 'ipfsd-ctl/src/config' {
  declare module.exports: any;
}

declare module 'ipfsd-ctl/src/endpoint/routes' {
  declare module.exports: any;
}

declare module 'ipfsd-ctl/src/endpoint/server.browser' {
  declare module.exports: any;
}

declare module 'ipfsd-ctl/src/endpoint/server' {
  declare module.exports: any;
}

declare module 'ipfsd-ctl/src/factory' {
  declare module.exports: any;
}

declare module 'ipfsd-ctl/src' {
  declare module.exports: any;
}

declare module 'ipfsd-ctl/src/ipfsd-client' {
  declare module.exports: any;
}

declare module 'ipfsd-ctl/src/ipfsd-daemon' {
  declare module.exports: any;
}

declare module 'ipfsd-ctl/src/ipfsd-in-proc' {
  declare module.exports: any;
}

declare module 'ipfsd-ctl/src/utils.browser' {
  declare module.exports: any;
}

declare module 'ipfsd-ctl/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ipfsd-ctl/dist/index.min.js' {
  declare module.exports: $Exports<'ipfsd-ctl/dist/index.min'>;
}
declare module 'ipfsd-ctl/src/config.js' {
  declare module.exports: $Exports<'ipfsd-ctl/src/config'>;
}
declare module 'ipfsd-ctl/src/endpoint/routes.js' {
  declare module.exports: $Exports<'ipfsd-ctl/src/endpoint/routes'>;
}
declare module 'ipfsd-ctl/src/endpoint/server.browser.js' {
  declare module.exports: $Exports<'ipfsd-ctl/src/endpoint/server.browser'>;
}
declare module 'ipfsd-ctl/src/endpoint/server.js' {
  declare module.exports: $Exports<'ipfsd-ctl/src/endpoint/server'>;
}
declare module 'ipfsd-ctl/src/factory.js' {
  declare module.exports: $Exports<'ipfsd-ctl/src/factory'>;
}
declare module 'ipfsd-ctl/src/index' {
  declare module.exports: $Exports<'ipfsd-ctl/src'>;
}
declare module 'ipfsd-ctl/src/index.js' {
  declare module.exports: $Exports<'ipfsd-ctl/src'>;
}
declare module 'ipfsd-ctl/src/ipfsd-client.js' {
  declare module.exports: $Exports<'ipfsd-ctl/src/ipfsd-client'>;
}
declare module 'ipfsd-ctl/src/ipfsd-daemon.js' {
  declare module.exports: $Exports<'ipfsd-ctl/src/ipfsd-daemon'>;
}
declare module 'ipfsd-ctl/src/ipfsd-in-proc.js' {
  declare module.exports: $Exports<'ipfsd-ctl/src/ipfsd-in-proc'>;
}
declare module 'ipfsd-ctl/src/utils.browser.js' {
  declare module.exports: $Exports<'ipfsd-ctl/src/utils.browser'>;
}
declare module 'ipfsd-ctl/src/utils.js' {
  declare module.exports: $Exports<'ipfsd-ctl/src/utils'>;
}
