// flow-typed signature: a87a00fcd1bc44c4ad2156845d570094
// flow-typed version: <<STUB>>/ipfs_v^0.27.7/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ipfs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ipfs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ipfs/dist/index' {
  declare module.exports: any;
}

declare module 'ipfs/dist/index.min' {
  declare module.exports: any;
}

declare module 'ipfs/examples/browser-browserify/src/index' {
  declare module.exports: any;
}

declare module 'ipfs/examples/browser-video-streaming/streaming' {
  declare module.exports: any;
}

declare module 'ipfs/examples/browser-webpack/server' {
  declare module.exports: any;
}

declare module 'ipfs/examples/browser-webpack/src/components/app' {
  declare module.exports: any;
}

declare module 'ipfs/examples/browser-webpack/src/components/index' {
  declare module.exports: any;
}

declare module 'ipfs/examples/browser-webpack/webpack.config' {
  declare module.exports: any;
}

declare module 'ipfs/examples/exchange-files-in-browser/public/app' {
  declare module.exports: any;
}

declare module 'ipfs/examples/ipfs-101/1' {
  declare module.exports: any;
}

declare module 'ipfs/examples/run-in-electron/main' {
  declare module.exports: any;
}

declare module 'ipfs/examples/run-in-electron/renderer' {
  declare module.exports: any;
}

declare module 'ipfs/examples/traverse-ipld-graphs/create-node' {
  declare module.exports: any;
}

declare module 'ipfs/examples/traverse-ipld-graphs/eth' {
  declare module.exports: any;
}

declare module 'ipfs/examples/traverse-ipld-graphs/get-path-accross-formats' {
  declare module.exports: any;
}

declare module 'ipfs/examples/traverse-ipld-graphs/get-path' {
  declare module.exports: any;
}

declare module 'ipfs/examples/traverse-ipld-graphs/get' {
  declare module.exports: any;
}

declare module 'ipfs/examples/traverse-ipld-graphs/git' {
  declare module.exports: any;
}

declare module 'ipfs/examples/traverse-ipld-graphs/put' {
  declare module.exports: any;
}

declare module 'ipfs/examples/traverse-ipld-graphs/tree' {
  declare module.exports: any;
}

declare module 'ipfs/src/cli/bin' {
  declare module.exports: any;
}

declare module 'ipfs/src/cli/commands/bitswap' {
  declare module.exports: any;
}

declare module 'ipfs/src/cli/commands/bitswap/stat' {
  declare module.exports: any;
}

declare module 'ipfs/src/cli/commands/bitswap/unwant' {
  declare module.exports: any;
}

declare module 'ipfs/src/cli/commands/bitswap/wantlist' {
  declare module.exports: any;
}

declare module 'ipfs/src/cli/commands/block' {
  declare module.exports: any;
}

declare module 'ipfs/src/cli/commands/block/get' {
  declare module.exports: any;
}

declare module 'ipfs/src/cli/commands/block/put' {
  declare module.exports: any;
}

declare module 'ipfs/src/cli/commands/block/rm' {
  declare module.exports: any;
}

declare module 'ipfs/src/cli/commands/block/stat' {
  declare module.exports: any;
}

declare module 'ipfs/src/cli/commands/bootstrap' {
  declare module.exports: any;
}

declare module 'ipfs/src/cli/commands/bootstrap/add' {
  declare module.exports: any;
}

declare module 'ipfs/src/cli/commands/bootstrap/list' {
  declare module.exports: any;
}

declare module 'ipfs/src/cli/commands/bootstrap/rm' {
  declare module.exports: any;
}

declare module 'ipfs/src/cli/commands/commands' {
  declare module.exports: any;
}

declare module 'ipfs/src/cli/commands/config' {
  declare module.exports: any;
}

declare module 'ipfs/src/cli/commands/config/edit' {
  declare module.exports: any;
}

declare module 'ipfs/src/cli/commands/config/replace' {
  declare module.exports: any;
}

declare module 'ipfs/src/cli/commands/config/show' {
  declare module.exports: any;
}

declare module 'ipfs/src/cli/commands/daemon' {
  declare module.exports: any;
}

declare module 'ipfs/src/cli/commands/dag' {
  declare module.exports: any;
}

declare module 'ipfs/src/cli/commands/dag/get' {
  declare module.exports: any;
}

declare module 'ipfs/src/cli/commands/dns' {
  declare module.exports: any;
}

declare module 'ipfs/src/cli/commands/file' {
  declare module.exports: any;
}

declare module 'ipfs/src/cli/commands/file/ls' {
  declare module.exports: any;
}

declare module 'ipfs/src/cli/commands/files' {
  declare module.exports: any;
}

declare module 'ipfs/src/cli/commands/files/add' {
  declare module.exports: any;
}

declare module 'ipfs/src/cli/commands/files/cat' {
  declare module.exports: any;
}

declare module 'ipfs/src/cli/commands/files/get' {
  declare module.exports: any;
}

declare module 'ipfs/src/cli/commands/id' {
  declare module.exports: any;
}

declare module 'ipfs/src/cli/commands/init' {
  declare module.exports: any;
}

declare module 'ipfs/src/cli/commands/ls' {
  declare module.exports: any;
}

declare module 'ipfs/src/cli/commands/object' {
  declare module.exports: any;
}

declare module 'ipfs/src/cli/commands/object/data' {
  declare module.exports: any;
}

declare module 'ipfs/src/cli/commands/object/get' {
  declare module.exports: any;
}

declare module 'ipfs/src/cli/commands/object/links' {
  declare module.exports: any;
}

declare module 'ipfs/src/cli/commands/object/new' {
  declare module.exports: any;
}

declare module 'ipfs/src/cli/commands/object/patch' {
  declare module.exports: any;
}

declare module 'ipfs/src/cli/commands/object/patch/add-link' {
  declare module.exports: any;
}

declare module 'ipfs/src/cli/commands/object/patch/append-data' {
  declare module.exports: any;
}

declare module 'ipfs/src/cli/commands/object/patch/rm-link' {
  declare module.exports: any;
}

declare module 'ipfs/src/cli/commands/object/patch/set-data' {
  declare module.exports: any;
}

declare module 'ipfs/src/cli/commands/object/put' {
  declare module.exports: any;
}

declare module 'ipfs/src/cli/commands/object/stat' {
  declare module.exports: any;
}

declare module 'ipfs/src/cli/commands/pubsub' {
  declare module.exports: any;
}

declare module 'ipfs/src/cli/commands/pubsub/ls' {
  declare module.exports: any;
}

declare module 'ipfs/src/cli/commands/pubsub/peers' {
  declare module.exports: any;
}

declare module 'ipfs/src/cli/commands/pubsub/pub' {
  declare module.exports: any;
}

declare module 'ipfs/src/cli/commands/pubsub/sub' {
  declare module.exports: any;
}

declare module 'ipfs/src/cli/commands/repo' {
  declare module.exports: any;
}

declare module 'ipfs/src/cli/commands/repo/gc' {
  declare module.exports: any;
}

declare module 'ipfs/src/cli/commands/repo/init' {
  declare module.exports: any;
}

declare module 'ipfs/src/cli/commands/repo/version' {
  declare module.exports: any;
}

declare module 'ipfs/src/cli/commands/swarm' {
  declare module.exports: any;
}

declare module 'ipfs/src/cli/commands/swarm/addrs' {
  declare module.exports: any;
}

declare module 'ipfs/src/cli/commands/swarm/addrs/local' {
  declare module.exports: any;
}

declare module 'ipfs/src/cli/commands/swarm/connect' {
  declare module.exports: any;
}

declare module 'ipfs/src/cli/commands/swarm/disconnect' {
  declare module.exports: any;
}

declare module 'ipfs/src/cli/commands/swarm/peers' {
  declare module.exports: any;
}

declare module 'ipfs/src/cli/commands/version' {
  declare module.exports: any;
}

declare module 'ipfs/src/cli/utils' {
  declare module.exports: any;
}

declare module 'ipfs/src/core/boot' {
  declare module.exports: any;
}

declare module 'ipfs/src/core/components/bitswap' {
  declare module.exports: any;
}

declare module 'ipfs/src/core/components/block' {
  declare module.exports: any;
}

declare module 'ipfs/src/core/components/bootstrap' {
  declare module.exports: any;
}

declare module 'ipfs/src/core/components/config' {
  declare module.exports: any;
}

declare module 'ipfs/src/core/components/dag' {
  declare module.exports: any;
}

declare module 'ipfs/src/core/components/dht' {
  declare module.exports: any;
}

declare module 'ipfs/src/core/components/dns' {
  declare module.exports: any;
}

declare module 'ipfs/src/core/components/files' {
  declare module.exports: any;
}

declare module 'ipfs/src/core/components/id' {
  declare module.exports: any;
}

declare module 'ipfs/src/core/components/index' {
  declare module.exports: any;
}

declare module 'ipfs/src/core/components/init-assets' {
  declare module.exports: any;
}

declare module 'ipfs/src/core/components/init' {
  declare module.exports: any;
}

declare module 'ipfs/src/core/components/is-online' {
  declare module.exports: any;
}

declare module 'ipfs/src/core/components/libp2p' {
  declare module.exports: any;
}

declare module 'ipfs/src/core/components/no-floodsub' {
  declare module.exports: any;
}

declare module 'ipfs/src/core/components/object' {
  declare module.exports: any;
}

declare module 'ipfs/src/core/components/ping' {
  declare module.exports: any;
}

declare module 'ipfs/src/core/components/pre-start' {
  declare module.exports: any;
}

declare module 'ipfs/src/core/components/pubsub' {
  declare module.exports: any;
}

declare module 'ipfs/src/core/components/repo' {
  declare module.exports: any;
}

declare module 'ipfs/src/core/components/start' {
  declare module.exports: any;
}

declare module 'ipfs/src/core/components/stop' {
  declare module.exports: any;
}

declare module 'ipfs/src/core/components/swarm' {
  declare module.exports: any;
}

declare module 'ipfs/src/core/components/version' {
  declare module.exports: any;
}

declare module 'ipfs/src/core/index' {
  declare module.exports: any;
}

declare module 'ipfs/src/core/runtime/dns-browser' {
  declare module.exports: any;
}

declare module 'ipfs/src/core/runtime/dns-nodejs' {
  declare module.exports: any;
}

declare module 'ipfs/src/core/runtime/libp2p-browser' {
  declare module.exports: any;
}

declare module 'ipfs/src/core/runtime/libp2p-nodejs' {
  declare module.exports: any;
}

declare module 'ipfs/src/core/runtime/repo-browser' {
  declare module.exports: any;
}

declare module 'ipfs/src/core/runtime/repo-nodejs' {
  declare module.exports: any;
}

declare module 'ipfs/src/core/state' {
  declare module.exports: any;
}

declare module 'ipfs/src/core/utils' {
  declare module.exports: any;
}

declare module 'ipfs/src/http/api/resources/bitswap' {
  declare module.exports: any;
}

declare module 'ipfs/src/http/api/resources/block' {
  declare module.exports: any;
}

declare module 'ipfs/src/http/api/resources/bootstrap' {
  declare module.exports: any;
}

declare module 'ipfs/src/http/api/resources/config' {
  declare module.exports: any;
}

declare module 'ipfs/src/http/api/resources/dns' {
  declare module.exports: any;
}

declare module 'ipfs/src/http/api/resources/file' {
  declare module.exports: any;
}

declare module 'ipfs/src/http/api/resources/files' {
  declare module.exports: any;
}

declare module 'ipfs/src/http/api/resources/id' {
  declare module.exports: any;
}

declare module 'ipfs/src/http/api/resources/index' {
  declare module.exports: any;
}

declare module 'ipfs/src/http/api/resources/object' {
  declare module.exports: any;
}

declare module 'ipfs/src/http/api/resources/pubsub' {
  declare module.exports: any;
}

declare module 'ipfs/src/http/api/resources/repo' {
  declare module.exports: any;
}

declare module 'ipfs/src/http/api/resources/swarm' {
  declare module.exports: any;
}

declare module 'ipfs/src/http/api/resources/version' {
  declare module.exports: any;
}

declare module 'ipfs/src/http/api/routes/bitswap' {
  declare module.exports: any;
}

declare module 'ipfs/src/http/api/routes/block' {
  declare module.exports: any;
}

declare module 'ipfs/src/http/api/routes/bootstrap' {
  declare module.exports: any;
}

declare module 'ipfs/src/http/api/routes/config' {
  declare module.exports: any;
}

declare module 'ipfs/src/http/api/routes/debug' {
  declare module.exports: any;
}

declare module 'ipfs/src/http/api/routes/dns' {
  declare module.exports: any;
}

declare module 'ipfs/src/http/api/routes/file' {
  declare module.exports: any;
}

declare module 'ipfs/src/http/api/routes/files' {
  declare module.exports: any;
}

declare module 'ipfs/src/http/api/routes/id' {
  declare module.exports: any;
}

declare module 'ipfs/src/http/api/routes/index' {
  declare module.exports: any;
}

declare module 'ipfs/src/http/api/routes/object' {
  declare module.exports: any;
}

declare module 'ipfs/src/http/api/routes/pubsub' {
  declare module.exports: any;
}

declare module 'ipfs/src/http/api/routes/repo' {
  declare module.exports: any;
}

declare module 'ipfs/src/http/api/routes/swarm' {
  declare module.exports: any;
}

declare module 'ipfs/src/http/api/routes/version' {
  declare module.exports: any;
}

declare module 'ipfs/src/http/api/routes/webui' {
  declare module.exports: any;
}

declare module 'ipfs/src/http/error-handler' {
  declare module.exports: any;
}

declare module 'ipfs/src/http/gateway/dir-view/index' {
  declare module.exports: any;
}

declare module 'ipfs/src/http/gateway/dir-view/style' {
  declare module.exports: any;
}

declare module 'ipfs/src/http/gateway/resolver' {
  declare module.exports: any;
}

declare module 'ipfs/src/http/gateway/resources/gateway' {
  declare module.exports: any;
}

declare module 'ipfs/src/http/gateway/resources/index' {
  declare module.exports: any;
}

declare module 'ipfs/src/http/gateway/routes/gateway' {
  declare module.exports: any;
}

declare module 'ipfs/src/http/gateway/routes/index' {
  declare module.exports: any;
}

declare module 'ipfs/src/http/gateway/utils/path' {
  declare module.exports: any;
}

declare module 'ipfs/src/http/index' {
  declare module.exports: any;
}

declare module 'ipfs/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ipfs/dist/index.js' {
  declare module.exports: $Exports<'ipfs/dist/index'>;
}
declare module 'ipfs/dist/index.min.js' {
  declare module.exports: $Exports<'ipfs/dist/index.min'>;
}
declare module 'ipfs/examples/browser-browserify/src/index.js' {
  declare module.exports: $Exports<'ipfs/examples/browser-browserify/src/index'>;
}
declare module 'ipfs/examples/browser-video-streaming/streaming.js' {
  declare module.exports: $Exports<'ipfs/examples/browser-video-streaming/streaming'>;
}
declare module 'ipfs/examples/browser-webpack/server.js' {
  declare module.exports: $Exports<'ipfs/examples/browser-webpack/server'>;
}
declare module 'ipfs/examples/browser-webpack/src/components/app.js' {
  declare module.exports: $Exports<'ipfs/examples/browser-webpack/src/components/app'>;
}
declare module 'ipfs/examples/browser-webpack/src/components/index.js' {
  declare module.exports: $Exports<'ipfs/examples/browser-webpack/src/components/index'>;
}
declare module 'ipfs/examples/browser-webpack/webpack.config.js' {
  declare module.exports: $Exports<'ipfs/examples/browser-webpack/webpack.config'>;
}
declare module 'ipfs/examples/exchange-files-in-browser/public/app.js' {
  declare module.exports: $Exports<'ipfs/examples/exchange-files-in-browser/public/app'>;
}
declare module 'ipfs/examples/ipfs-101/1.js' {
  declare module.exports: $Exports<'ipfs/examples/ipfs-101/1'>;
}
declare module 'ipfs/examples/run-in-electron/main.js' {
  declare module.exports: $Exports<'ipfs/examples/run-in-electron/main'>;
}
declare module 'ipfs/examples/run-in-electron/renderer.js' {
  declare module.exports: $Exports<'ipfs/examples/run-in-electron/renderer'>;
}
declare module 'ipfs/examples/traverse-ipld-graphs/create-node.js' {
  declare module.exports: $Exports<'ipfs/examples/traverse-ipld-graphs/create-node'>;
}
declare module 'ipfs/examples/traverse-ipld-graphs/eth.js' {
  declare module.exports: $Exports<'ipfs/examples/traverse-ipld-graphs/eth'>;
}
declare module 'ipfs/examples/traverse-ipld-graphs/get-path-accross-formats.js' {
  declare module.exports: $Exports<'ipfs/examples/traverse-ipld-graphs/get-path-accross-formats'>;
}
declare module 'ipfs/examples/traverse-ipld-graphs/get-path.js' {
  declare module.exports: $Exports<'ipfs/examples/traverse-ipld-graphs/get-path'>;
}
declare module 'ipfs/examples/traverse-ipld-graphs/get.js' {
  declare module.exports: $Exports<'ipfs/examples/traverse-ipld-graphs/get'>;
}
declare module 'ipfs/examples/traverse-ipld-graphs/git.js' {
  declare module.exports: $Exports<'ipfs/examples/traverse-ipld-graphs/git'>;
}
declare module 'ipfs/examples/traverse-ipld-graphs/put.js' {
  declare module.exports: $Exports<'ipfs/examples/traverse-ipld-graphs/put'>;
}
declare module 'ipfs/examples/traverse-ipld-graphs/tree.js' {
  declare module.exports: $Exports<'ipfs/examples/traverse-ipld-graphs/tree'>;
}
declare module 'ipfs/src/cli/bin.js' {
  declare module.exports: $Exports<'ipfs/src/cli/bin'>;
}
declare module 'ipfs/src/cli/commands/bitswap.js' {
  declare module.exports: $Exports<'ipfs/src/cli/commands/bitswap'>;
}
declare module 'ipfs/src/cli/commands/bitswap/stat.js' {
  declare module.exports: $Exports<'ipfs/src/cli/commands/bitswap/stat'>;
}
declare module 'ipfs/src/cli/commands/bitswap/unwant.js' {
  declare module.exports: $Exports<'ipfs/src/cli/commands/bitswap/unwant'>;
}
declare module 'ipfs/src/cli/commands/bitswap/wantlist.js' {
  declare module.exports: $Exports<'ipfs/src/cli/commands/bitswap/wantlist'>;
}
declare module 'ipfs/src/cli/commands/block.js' {
  declare module.exports: $Exports<'ipfs/src/cli/commands/block'>;
}
declare module 'ipfs/src/cli/commands/block/get.js' {
  declare module.exports: $Exports<'ipfs/src/cli/commands/block/get'>;
}
declare module 'ipfs/src/cli/commands/block/put.js' {
  declare module.exports: $Exports<'ipfs/src/cli/commands/block/put'>;
}
declare module 'ipfs/src/cli/commands/block/rm.js' {
  declare module.exports: $Exports<'ipfs/src/cli/commands/block/rm'>;
}
declare module 'ipfs/src/cli/commands/block/stat.js' {
  declare module.exports: $Exports<'ipfs/src/cli/commands/block/stat'>;
}
declare module 'ipfs/src/cli/commands/bootstrap.js' {
  declare module.exports: $Exports<'ipfs/src/cli/commands/bootstrap'>;
}
declare module 'ipfs/src/cli/commands/bootstrap/add.js' {
  declare module.exports: $Exports<'ipfs/src/cli/commands/bootstrap/add'>;
}
declare module 'ipfs/src/cli/commands/bootstrap/list.js' {
  declare module.exports: $Exports<'ipfs/src/cli/commands/bootstrap/list'>;
}
declare module 'ipfs/src/cli/commands/bootstrap/rm.js' {
  declare module.exports: $Exports<'ipfs/src/cli/commands/bootstrap/rm'>;
}
declare module 'ipfs/src/cli/commands/commands.js' {
  declare module.exports: $Exports<'ipfs/src/cli/commands/commands'>;
}
declare module 'ipfs/src/cli/commands/config.js' {
  declare module.exports: $Exports<'ipfs/src/cli/commands/config'>;
}
declare module 'ipfs/src/cli/commands/config/edit.js' {
  declare module.exports: $Exports<'ipfs/src/cli/commands/config/edit'>;
}
declare module 'ipfs/src/cli/commands/config/replace.js' {
  declare module.exports: $Exports<'ipfs/src/cli/commands/config/replace'>;
}
declare module 'ipfs/src/cli/commands/config/show.js' {
  declare module.exports: $Exports<'ipfs/src/cli/commands/config/show'>;
}
declare module 'ipfs/src/cli/commands/daemon.js' {
  declare module.exports: $Exports<'ipfs/src/cli/commands/daemon'>;
}
declare module 'ipfs/src/cli/commands/dag.js' {
  declare module.exports: $Exports<'ipfs/src/cli/commands/dag'>;
}
declare module 'ipfs/src/cli/commands/dag/get.js' {
  declare module.exports: $Exports<'ipfs/src/cli/commands/dag/get'>;
}
declare module 'ipfs/src/cli/commands/dns.js' {
  declare module.exports: $Exports<'ipfs/src/cli/commands/dns'>;
}
declare module 'ipfs/src/cli/commands/file.js' {
  declare module.exports: $Exports<'ipfs/src/cli/commands/file'>;
}
declare module 'ipfs/src/cli/commands/file/ls.js' {
  declare module.exports: $Exports<'ipfs/src/cli/commands/file/ls'>;
}
declare module 'ipfs/src/cli/commands/files.js' {
  declare module.exports: $Exports<'ipfs/src/cli/commands/files'>;
}
declare module 'ipfs/src/cli/commands/files/add.js' {
  declare module.exports: $Exports<'ipfs/src/cli/commands/files/add'>;
}
declare module 'ipfs/src/cli/commands/files/cat.js' {
  declare module.exports: $Exports<'ipfs/src/cli/commands/files/cat'>;
}
declare module 'ipfs/src/cli/commands/files/get.js' {
  declare module.exports: $Exports<'ipfs/src/cli/commands/files/get'>;
}
declare module 'ipfs/src/cli/commands/id.js' {
  declare module.exports: $Exports<'ipfs/src/cli/commands/id'>;
}
declare module 'ipfs/src/cli/commands/init.js' {
  declare module.exports: $Exports<'ipfs/src/cli/commands/init'>;
}
declare module 'ipfs/src/cli/commands/ls.js' {
  declare module.exports: $Exports<'ipfs/src/cli/commands/ls'>;
}
declare module 'ipfs/src/cli/commands/object.js' {
  declare module.exports: $Exports<'ipfs/src/cli/commands/object'>;
}
declare module 'ipfs/src/cli/commands/object/data.js' {
  declare module.exports: $Exports<'ipfs/src/cli/commands/object/data'>;
}
declare module 'ipfs/src/cli/commands/object/get.js' {
  declare module.exports: $Exports<'ipfs/src/cli/commands/object/get'>;
}
declare module 'ipfs/src/cli/commands/object/links.js' {
  declare module.exports: $Exports<'ipfs/src/cli/commands/object/links'>;
}
declare module 'ipfs/src/cli/commands/object/new.js' {
  declare module.exports: $Exports<'ipfs/src/cli/commands/object/new'>;
}
declare module 'ipfs/src/cli/commands/object/patch.js' {
  declare module.exports: $Exports<'ipfs/src/cli/commands/object/patch'>;
}
declare module 'ipfs/src/cli/commands/object/patch/add-link.js' {
  declare module.exports: $Exports<'ipfs/src/cli/commands/object/patch/add-link'>;
}
declare module 'ipfs/src/cli/commands/object/patch/append-data.js' {
  declare module.exports: $Exports<'ipfs/src/cli/commands/object/patch/append-data'>;
}
declare module 'ipfs/src/cli/commands/object/patch/rm-link.js' {
  declare module.exports: $Exports<'ipfs/src/cli/commands/object/patch/rm-link'>;
}
declare module 'ipfs/src/cli/commands/object/patch/set-data.js' {
  declare module.exports: $Exports<'ipfs/src/cli/commands/object/patch/set-data'>;
}
declare module 'ipfs/src/cli/commands/object/put.js' {
  declare module.exports: $Exports<'ipfs/src/cli/commands/object/put'>;
}
declare module 'ipfs/src/cli/commands/object/stat.js' {
  declare module.exports: $Exports<'ipfs/src/cli/commands/object/stat'>;
}
declare module 'ipfs/src/cli/commands/pubsub.js' {
  declare module.exports: $Exports<'ipfs/src/cli/commands/pubsub'>;
}
declare module 'ipfs/src/cli/commands/pubsub/ls.js' {
  declare module.exports: $Exports<'ipfs/src/cli/commands/pubsub/ls'>;
}
declare module 'ipfs/src/cli/commands/pubsub/peers.js' {
  declare module.exports: $Exports<'ipfs/src/cli/commands/pubsub/peers'>;
}
declare module 'ipfs/src/cli/commands/pubsub/pub.js' {
  declare module.exports: $Exports<'ipfs/src/cli/commands/pubsub/pub'>;
}
declare module 'ipfs/src/cli/commands/pubsub/sub.js' {
  declare module.exports: $Exports<'ipfs/src/cli/commands/pubsub/sub'>;
}
declare module 'ipfs/src/cli/commands/repo.js' {
  declare module.exports: $Exports<'ipfs/src/cli/commands/repo'>;
}
declare module 'ipfs/src/cli/commands/repo/gc.js' {
  declare module.exports: $Exports<'ipfs/src/cli/commands/repo/gc'>;
}
declare module 'ipfs/src/cli/commands/repo/init.js' {
  declare module.exports: $Exports<'ipfs/src/cli/commands/repo/init'>;
}
declare module 'ipfs/src/cli/commands/repo/version.js' {
  declare module.exports: $Exports<'ipfs/src/cli/commands/repo/version'>;
}
declare module 'ipfs/src/cli/commands/swarm.js' {
  declare module.exports: $Exports<'ipfs/src/cli/commands/swarm'>;
}
declare module 'ipfs/src/cli/commands/swarm/addrs.js' {
  declare module.exports: $Exports<'ipfs/src/cli/commands/swarm/addrs'>;
}
declare module 'ipfs/src/cli/commands/swarm/addrs/local.js' {
  declare module.exports: $Exports<'ipfs/src/cli/commands/swarm/addrs/local'>;
}
declare module 'ipfs/src/cli/commands/swarm/connect.js' {
  declare module.exports: $Exports<'ipfs/src/cli/commands/swarm/connect'>;
}
declare module 'ipfs/src/cli/commands/swarm/disconnect.js' {
  declare module.exports: $Exports<'ipfs/src/cli/commands/swarm/disconnect'>;
}
declare module 'ipfs/src/cli/commands/swarm/peers.js' {
  declare module.exports: $Exports<'ipfs/src/cli/commands/swarm/peers'>;
}
declare module 'ipfs/src/cli/commands/version.js' {
  declare module.exports: $Exports<'ipfs/src/cli/commands/version'>;
}
declare module 'ipfs/src/cli/utils.js' {
  declare module.exports: $Exports<'ipfs/src/cli/utils'>;
}
declare module 'ipfs/src/core/boot.js' {
  declare module.exports: $Exports<'ipfs/src/core/boot'>;
}
declare module 'ipfs/src/core/components/bitswap.js' {
  declare module.exports: $Exports<'ipfs/src/core/components/bitswap'>;
}
declare module 'ipfs/src/core/components/block.js' {
  declare module.exports: $Exports<'ipfs/src/core/components/block'>;
}
declare module 'ipfs/src/core/components/bootstrap.js' {
  declare module.exports: $Exports<'ipfs/src/core/components/bootstrap'>;
}
declare module 'ipfs/src/core/components/config.js' {
  declare module.exports: $Exports<'ipfs/src/core/components/config'>;
}
declare module 'ipfs/src/core/components/dag.js' {
  declare module.exports: $Exports<'ipfs/src/core/components/dag'>;
}
declare module 'ipfs/src/core/components/dht.js' {
  declare module.exports: $Exports<'ipfs/src/core/components/dht'>;
}
declare module 'ipfs/src/core/components/dns.js' {
  declare module.exports: $Exports<'ipfs/src/core/components/dns'>;
}
declare module 'ipfs/src/core/components/files.js' {
  declare module.exports: $Exports<'ipfs/src/core/components/files'>;
}
declare module 'ipfs/src/core/components/id.js' {
  declare module.exports: $Exports<'ipfs/src/core/components/id'>;
}
declare module 'ipfs/src/core/components/index.js' {
  declare module.exports: $Exports<'ipfs/src/core/components/index'>;
}
declare module 'ipfs/src/core/components/init-assets.js' {
  declare module.exports: $Exports<'ipfs/src/core/components/init-assets'>;
}
declare module 'ipfs/src/core/components/init.js' {
  declare module.exports: $Exports<'ipfs/src/core/components/init'>;
}
declare module 'ipfs/src/core/components/is-online.js' {
  declare module.exports: $Exports<'ipfs/src/core/components/is-online'>;
}
declare module 'ipfs/src/core/components/libp2p.js' {
  declare module.exports: $Exports<'ipfs/src/core/components/libp2p'>;
}
declare module 'ipfs/src/core/components/no-floodsub.js' {
  declare module.exports: $Exports<'ipfs/src/core/components/no-floodsub'>;
}
declare module 'ipfs/src/core/components/object.js' {
  declare module.exports: $Exports<'ipfs/src/core/components/object'>;
}
declare module 'ipfs/src/core/components/ping.js' {
  declare module.exports: $Exports<'ipfs/src/core/components/ping'>;
}
declare module 'ipfs/src/core/components/pre-start.js' {
  declare module.exports: $Exports<'ipfs/src/core/components/pre-start'>;
}
declare module 'ipfs/src/core/components/pubsub.js' {
  declare module.exports: $Exports<'ipfs/src/core/components/pubsub'>;
}
declare module 'ipfs/src/core/components/repo.js' {
  declare module.exports: $Exports<'ipfs/src/core/components/repo'>;
}
declare module 'ipfs/src/core/components/start.js' {
  declare module.exports: $Exports<'ipfs/src/core/components/start'>;
}
declare module 'ipfs/src/core/components/stop.js' {
  declare module.exports: $Exports<'ipfs/src/core/components/stop'>;
}
declare module 'ipfs/src/core/components/swarm.js' {
  declare module.exports: $Exports<'ipfs/src/core/components/swarm'>;
}
declare module 'ipfs/src/core/components/version.js' {
  declare module.exports: $Exports<'ipfs/src/core/components/version'>;
}
declare module 'ipfs/src/core/index.js' {
  declare module.exports: $Exports<'ipfs/src/core/index'>;
}
declare module 'ipfs/src/core/runtime/dns-browser.js' {
  declare module.exports: $Exports<'ipfs/src/core/runtime/dns-browser'>;
}
declare module 'ipfs/src/core/runtime/dns-nodejs.js' {
  declare module.exports: $Exports<'ipfs/src/core/runtime/dns-nodejs'>;
}
declare module 'ipfs/src/core/runtime/libp2p-browser.js' {
  declare module.exports: $Exports<'ipfs/src/core/runtime/libp2p-browser'>;
}
declare module 'ipfs/src/core/runtime/libp2p-nodejs.js' {
  declare module.exports: $Exports<'ipfs/src/core/runtime/libp2p-nodejs'>;
}
declare module 'ipfs/src/core/runtime/repo-browser.js' {
  declare module.exports: $Exports<'ipfs/src/core/runtime/repo-browser'>;
}
declare module 'ipfs/src/core/runtime/repo-nodejs.js' {
  declare module.exports: $Exports<'ipfs/src/core/runtime/repo-nodejs'>;
}
declare module 'ipfs/src/core/state.js' {
  declare module.exports: $Exports<'ipfs/src/core/state'>;
}
declare module 'ipfs/src/core/utils.js' {
  declare module.exports: $Exports<'ipfs/src/core/utils'>;
}
declare module 'ipfs/src/http/api/resources/bitswap.js' {
  declare module.exports: $Exports<'ipfs/src/http/api/resources/bitswap'>;
}
declare module 'ipfs/src/http/api/resources/block.js' {
  declare module.exports: $Exports<'ipfs/src/http/api/resources/block'>;
}
declare module 'ipfs/src/http/api/resources/bootstrap.js' {
  declare module.exports: $Exports<'ipfs/src/http/api/resources/bootstrap'>;
}
declare module 'ipfs/src/http/api/resources/config.js' {
  declare module.exports: $Exports<'ipfs/src/http/api/resources/config'>;
}
declare module 'ipfs/src/http/api/resources/dns.js' {
  declare module.exports: $Exports<'ipfs/src/http/api/resources/dns'>;
}
declare module 'ipfs/src/http/api/resources/file.js' {
  declare module.exports: $Exports<'ipfs/src/http/api/resources/file'>;
}
declare module 'ipfs/src/http/api/resources/files.js' {
  declare module.exports: $Exports<'ipfs/src/http/api/resources/files'>;
}
declare module 'ipfs/src/http/api/resources/id.js' {
  declare module.exports: $Exports<'ipfs/src/http/api/resources/id'>;
}
declare module 'ipfs/src/http/api/resources/index.js' {
  declare module.exports: $Exports<'ipfs/src/http/api/resources/index'>;
}
declare module 'ipfs/src/http/api/resources/object.js' {
  declare module.exports: $Exports<'ipfs/src/http/api/resources/object'>;
}
declare module 'ipfs/src/http/api/resources/pubsub.js' {
  declare module.exports: $Exports<'ipfs/src/http/api/resources/pubsub'>;
}
declare module 'ipfs/src/http/api/resources/repo.js' {
  declare module.exports: $Exports<'ipfs/src/http/api/resources/repo'>;
}
declare module 'ipfs/src/http/api/resources/swarm.js' {
  declare module.exports: $Exports<'ipfs/src/http/api/resources/swarm'>;
}
declare module 'ipfs/src/http/api/resources/version.js' {
  declare module.exports: $Exports<'ipfs/src/http/api/resources/version'>;
}
declare module 'ipfs/src/http/api/routes/bitswap.js' {
  declare module.exports: $Exports<'ipfs/src/http/api/routes/bitswap'>;
}
declare module 'ipfs/src/http/api/routes/block.js' {
  declare module.exports: $Exports<'ipfs/src/http/api/routes/block'>;
}
declare module 'ipfs/src/http/api/routes/bootstrap.js' {
  declare module.exports: $Exports<'ipfs/src/http/api/routes/bootstrap'>;
}
declare module 'ipfs/src/http/api/routes/config.js' {
  declare module.exports: $Exports<'ipfs/src/http/api/routes/config'>;
}
declare module 'ipfs/src/http/api/routes/debug.js' {
  declare module.exports: $Exports<'ipfs/src/http/api/routes/debug'>;
}
declare module 'ipfs/src/http/api/routes/dns.js' {
  declare module.exports: $Exports<'ipfs/src/http/api/routes/dns'>;
}
declare module 'ipfs/src/http/api/routes/file.js' {
  declare module.exports: $Exports<'ipfs/src/http/api/routes/file'>;
}
declare module 'ipfs/src/http/api/routes/files.js' {
  declare module.exports: $Exports<'ipfs/src/http/api/routes/files'>;
}
declare module 'ipfs/src/http/api/routes/id.js' {
  declare module.exports: $Exports<'ipfs/src/http/api/routes/id'>;
}
declare module 'ipfs/src/http/api/routes/index.js' {
  declare module.exports: $Exports<'ipfs/src/http/api/routes/index'>;
}
declare module 'ipfs/src/http/api/routes/object.js' {
  declare module.exports: $Exports<'ipfs/src/http/api/routes/object'>;
}
declare module 'ipfs/src/http/api/routes/pubsub.js' {
  declare module.exports: $Exports<'ipfs/src/http/api/routes/pubsub'>;
}
declare module 'ipfs/src/http/api/routes/repo.js' {
  declare module.exports: $Exports<'ipfs/src/http/api/routes/repo'>;
}
declare module 'ipfs/src/http/api/routes/swarm.js' {
  declare module.exports: $Exports<'ipfs/src/http/api/routes/swarm'>;
}
declare module 'ipfs/src/http/api/routes/version.js' {
  declare module.exports: $Exports<'ipfs/src/http/api/routes/version'>;
}
declare module 'ipfs/src/http/api/routes/webui.js' {
  declare module.exports: $Exports<'ipfs/src/http/api/routes/webui'>;
}
declare module 'ipfs/src/http/error-handler.js' {
  declare module.exports: $Exports<'ipfs/src/http/error-handler'>;
}
declare module 'ipfs/src/http/gateway/dir-view/index.js' {
  declare module.exports: $Exports<'ipfs/src/http/gateway/dir-view/index'>;
}
declare module 'ipfs/src/http/gateway/dir-view/style.js' {
  declare module.exports: $Exports<'ipfs/src/http/gateway/dir-view/style'>;
}
declare module 'ipfs/src/http/gateway/resolver.js' {
  declare module.exports: $Exports<'ipfs/src/http/gateway/resolver'>;
}
declare module 'ipfs/src/http/gateway/resources/gateway.js' {
  declare module.exports: $Exports<'ipfs/src/http/gateway/resources/gateway'>;
}
declare module 'ipfs/src/http/gateway/resources/index.js' {
  declare module.exports: $Exports<'ipfs/src/http/gateway/resources/index'>;
}
declare module 'ipfs/src/http/gateway/routes/gateway.js' {
  declare module.exports: $Exports<'ipfs/src/http/gateway/routes/gateway'>;
}
declare module 'ipfs/src/http/gateway/routes/index.js' {
  declare module.exports: $Exports<'ipfs/src/http/gateway/routes/index'>;
}
declare module 'ipfs/src/http/gateway/utils/path.js' {
  declare module.exports: $Exports<'ipfs/src/http/gateway/utils/path'>;
}
declare module 'ipfs/src/http/index.js' {
  declare module.exports: $Exports<'ipfs/src/http/index'>;
}
declare module 'ipfs/src/index.js' {
  declare module.exports: $Exports<'ipfs/src/index'>;
}
