// flow-typed signature: 6be10e0ad2a2937770e71e2fe8a6519a
// flow-typed version: <<STUB>>/observed-remove_v^1.4.2/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'observed-remove'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'observed-remove' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'observed-remove/dist/index' {
  declare module.exports: any;
}

declare module 'observed-remove/dist/map' {
  declare module.exports: any;
}

declare module 'observed-remove/dist/set' {
  declare module.exports: any;
}

declare module 'observed-remove/flow-typed/npm/babel-eslint_vx.x.x' {
  declare module.exports: any;
}

declare module 'observed-remove/flow-typed/npm/codecov_vx.x.x' {
  declare module.exports: any;
}

declare module 'observed-remove/flow-typed/npm/cross-env_vx.x.x' {
  declare module.exports: any;
}

declare module 'observed-remove/flow-typed/npm/directed-graph-map_vx.x.x' {
  declare module.exports: any;
}

declare module 'observed-remove/flow-typed/npm/documentation_vx.x.x' {
  declare module.exports: any;
}

declare module 'observed-remove/flow-typed/npm/eslint_vx.x.x' {
  declare module.exports: any;
}

declare module 'observed-remove/flow-typed/npm/eslint-config-bunchtogether_vx.x.x' {
  declare module.exports: any;
}

declare module 'observed-remove/flow-typed/npm/eslint-plugin-flowtype_vx.x.x' {
  declare module.exports: any;
}

declare module 'observed-remove/flow-typed/npm/eslint-plugin-flowtype-errors_vx.x.x' {
  declare module.exports: any;
}

declare module 'observed-remove/flow-typed/npm/eslint-plugin-import_vx.x.x' {
  declare module.exports: any;
}

declare module 'observed-remove/flow-typed/npm/eslint-plugin-jest_vx.x.x' {
  declare module.exports: any;
}

declare module 'observed-remove/flow-typed/npm/eslint-plugin-jsx-a11y_vx.x.x' {
  declare module.exports: any;
}

declare module 'observed-remove/flow-typed/npm/eslint-plugin-react_vx.x.x' {
  declare module.exports: any;
}

declare module 'observed-remove/flow-typed/npm/expect_vx.x.x' {
  declare module.exports: any;
}

declare module 'observed-remove/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module 'observed-remove/flow-typed/npm/flow-remove-types_vx.x.x' {
  declare module.exports: any;
}

declare module 'observed-remove/flow-typed/npm/flow-typed_vx.x.x' {
  declare module.exports: any;
}

declare module 'observed-remove/flow-typed/npm/jest_v22.x.x' {
  declare module.exports: any;
}

declare module 'observed-remove/flow-typed/npm/jest-flow-transform_vx.x.x' {
  declare module.exports: any;
}

declare module 'observed-remove/flow-typed/npm/json-stringify-deterministic_vx.x.x' {
  declare module.exports: any;
}

declare module 'observed-remove/flow-typed/npm/murmur-hash_vx.x.x' {
  declare module.exports: any;
}

declare module 'observed-remove/flow-typed/npm/pre-commit_vx.x.x' {
  declare module.exports: any;
}

declare module 'observed-remove/flow-typed/npm/uuid_v3.x.x' {
  declare module.exports: any;
}

declare module 'observed-remove/src/index' {
  declare module.exports: any;
}

declare module 'observed-remove/src/map' {
  declare module.exports: any;
}

declare module 'observed-remove/src/set' {
  declare module.exports: any;
}

declare module 'observed-remove/tests/lib/values' {
  declare module.exports: any;
}

declare module 'observed-remove/tests/map.test' {
  declare module.exports: any;
}

declare module 'observed-remove/tests/set.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'observed-remove/dist/index.js' {
  declare module.exports: $Exports<'observed-remove/dist/index'>;
}
declare module 'observed-remove/dist/map.js' {
  declare module.exports: $Exports<'observed-remove/dist/map'>;
}
declare module 'observed-remove/dist/set.js' {
  declare module.exports: $Exports<'observed-remove/dist/set'>;
}
declare module 'observed-remove/flow-typed/npm/babel-eslint_vx.x.x.js' {
  declare module.exports: $Exports<'observed-remove/flow-typed/npm/babel-eslint_vx.x.x'>;
}
declare module 'observed-remove/flow-typed/npm/codecov_vx.x.x.js' {
  declare module.exports: $Exports<'observed-remove/flow-typed/npm/codecov_vx.x.x'>;
}
declare module 'observed-remove/flow-typed/npm/cross-env_vx.x.x.js' {
  declare module.exports: $Exports<'observed-remove/flow-typed/npm/cross-env_vx.x.x'>;
}
declare module 'observed-remove/flow-typed/npm/directed-graph-map_vx.x.x.js' {
  declare module.exports: $Exports<'observed-remove/flow-typed/npm/directed-graph-map_vx.x.x'>;
}
declare module 'observed-remove/flow-typed/npm/documentation_vx.x.x.js' {
  declare module.exports: $Exports<'observed-remove/flow-typed/npm/documentation_vx.x.x'>;
}
declare module 'observed-remove/flow-typed/npm/eslint_vx.x.x.js' {
  declare module.exports: $Exports<'observed-remove/flow-typed/npm/eslint_vx.x.x'>;
}
declare module 'observed-remove/flow-typed/npm/eslint-config-bunchtogether_vx.x.x.js' {
  declare module.exports: $Exports<'observed-remove/flow-typed/npm/eslint-config-bunchtogether_vx.x.x'>;
}
declare module 'observed-remove/flow-typed/npm/eslint-plugin-flowtype_vx.x.x.js' {
  declare module.exports: $Exports<'observed-remove/flow-typed/npm/eslint-plugin-flowtype_vx.x.x'>;
}
declare module 'observed-remove/flow-typed/npm/eslint-plugin-flowtype-errors_vx.x.x.js' {
  declare module.exports: $Exports<'observed-remove/flow-typed/npm/eslint-plugin-flowtype-errors_vx.x.x'>;
}
declare module 'observed-remove/flow-typed/npm/eslint-plugin-import_vx.x.x.js' {
  declare module.exports: $Exports<'observed-remove/flow-typed/npm/eslint-plugin-import_vx.x.x'>;
}
declare module 'observed-remove/flow-typed/npm/eslint-plugin-jest_vx.x.x.js' {
  declare module.exports: $Exports<'observed-remove/flow-typed/npm/eslint-plugin-jest_vx.x.x'>;
}
declare module 'observed-remove/flow-typed/npm/eslint-plugin-jsx-a11y_vx.x.x.js' {
  declare module.exports: $Exports<'observed-remove/flow-typed/npm/eslint-plugin-jsx-a11y_vx.x.x'>;
}
declare module 'observed-remove/flow-typed/npm/eslint-plugin-react_vx.x.x.js' {
  declare module.exports: $Exports<'observed-remove/flow-typed/npm/eslint-plugin-react_vx.x.x'>;
}
declare module 'observed-remove/flow-typed/npm/expect_vx.x.x.js' {
  declare module.exports: $Exports<'observed-remove/flow-typed/npm/expect_vx.x.x'>;
}
declare module 'observed-remove/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'observed-remove/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module 'observed-remove/flow-typed/npm/flow-remove-types_vx.x.x.js' {
  declare module.exports: $Exports<'observed-remove/flow-typed/npm/flow-remove-types_vx.x.x'>;
}
declare module 'observed-remove/flow-typed/npm/flow-typed_vx.x.x.js' {
  declare module.exports: $Exports<'observed-remove/flow-typed/npm/flow-typed_vx.x.x'>;
}
declare module 'observed-remove/flow-typed/npm/jest_v22.x.x.js' {
  declare module.exports: $Exports<'observed-remove/flow-typed/npm/jest_v22.x.x'>;
}
declare module 'observed-remove/flow-typed/npm/jest-flow-transform_vx.x.x.js' {
  declare module.exports: $Exports<'observed-remove/flow-typed/npm/jest-flow-transform_vx.x.x'>;
}
declare module 'observed-remove/flow-typed/npm/json-stringify-deterministic_vx.x.x.js' {
  declare module.exports: $Exports<'observed-remove/flow-typed/npm/json-stringify-deterministic_vx.x.x'>;
}
declare module 'observed-remove/flow-typed/npm/murmur-hash_vx.x.x.js' {
  declare module.exports: $Exports<'observed-remove/flow-typed/npm/murmur-hash_vx.x.x'>;
}
declare module 'observed-remove/flow-typed/npm/pre-commit_vx.x.x.js' {
  declare module.exports: $Exports<'observed-remove/flow-typed/npm/pre-commit_vx.x.x'>;
}
declare module 'observed-remove/flow-typed/npm/uuid_v3.x.x.js' {
  declare module.exports: $Exports<'observed-remove/flow-typed/npm/uuid_v3.x.x'>;
}
declare module 'observed-remove/src/index.js' {
  declare module.exports: $Exports<'observed-remove/src/index'>;
}
declare module 'observed-remove/src/map.js' {
  declare module.exports: $Exports<'observed-remove/src/map'>;
}
declare module 'observed-remove/src/set.js' {
  declare module.exports: $Exports<'observed-remove/src/set'>;
}
declare module 'observed-remove/tests/lib/values.js' {
  declare module.exports: $Exports<'observed-remove/tests/lib/values'>;
}
declare module 'observed-remove/tests/map.test.js' {
  declare module.exports: $Exports<'observed-remove/tests/map.test'>;
}
declare module 'observed-remove/tests/set.test.js' {
  declare module.exports: $Exports<'observed-remove/tests/set.test'>;
}
