// flow-typed signature: 2ec6dbd1cec28ad113e6e70f39239faf
// flow-typed version: <<STUB>>/stream-json_v^1.7.3/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stream-json'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stream-json' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'stream-json/Assembler' {
  declare module.exports: any;
}

declare module 'stream-json/Disassembler' {
  declare module.exports: any;
}

declare module 'stream-json/Emitter' {
  declare module.exports: any;
}

declare module 'stream-json/filters/Filter' {
  declare module.exports: any;
}

declare module 'stream-json/filters/FilterBase' {
  declare module.exports: any;
}

declare module 'stream-json/filters/Ignore' {
  declare module.exports: any;
}

declare module 'stream-json/filters/Pick' {
  declare module.exports: any;
}

declare module 'stream-json/filters/Replace' {
  declare module.exports: any;
}

declare module 'stream-json/jsonl/Parser' {
  declare module.exports: any;
}

declare module 'stream-json/jsonl/Stringer' {
  declare module.exports: any;
}

declare module 'stream-json/Parser' {
  declare module.exports: any;
}

declare module 'stream-json/streamers/StreamArray' {
  declare module.exports: any;
}

declare module 'stream-json/streamers/StreamBase' {
  declare module.exports: any;
}

declare module 'stream-json/streamers/StreamObject' {
  declare module.exports: any;
}

declare module 'stream-json/streamers/StreamValues' {
  declare module.exports: any;
}

declare module 'stream-json/Stringer' {
  declare module.exports: any;
}

declare module 'stream-json/utils/Batch' {
  declare module.exports: any;
}

declare module 'stream-json/utils/emit' {
  declare module.exports: any;
}

declare module 'stream-json/utils/Utf8Stream' {
  declare module.exports: any;
}

declare module 'stream-json/utils/Verifier' {
  declare module.exports: any;
}

declare module 'stream-json/utils/withParser' {
  declare module.exports: any;
}

// Filename aliases
declare module 'stream-json/Assembler.js' {
  declare module.exports: $Exports<'stream-json/Assembler'>;
}
declare module 'stream-json/Disassembler.js' {
  declare module.exports: $Exports<'stream-json/Disassembler'>;
}
declare module 'stream-json/Emitter.js' {
  declare module.exports: $Exports<'stream-json/Emitter'>;
}
declare module 'stream-json/filters/Filter.js' {
  declare module.exports: $Exports<'stream-json/filters/Filter'>;
}
declare module 'stream-json/filters/FilterBase.js' {
  declare module.exports: $Exports<'stream-json/filters/FilterBase'>;
}
declare module 'stream-json/filters/Ignore.js' {
  declare module.exports: $Exports<'stream-json/filters/Ignore'>;
}
declare module 'stream-json/filters/Pick.js' {
  declare module.exports: $Exports<'stream-json/filters/Pick'>;
}
declare module 'stream-json/filters/Replace.js' {
  declare module.exports: $Exports<'stream-json/filters/Replace'>;
}
declare module 'stream-json/index' {
  declare module.exports: $Exports<'stream-json'>;
}
declare module 'stream-json/index.js' {
  declare module.exports: $Exports<'stream-json'>;
}
declare module 'stream-json/jsonl/Parser.js' {
  declare module.exports: $Exports<'stream-json/jsonl/Parser'>;
}
declare module 'stream-json/jsonl/Stringer.js' {
  declare module.exports: $Exports<'stream-json/jsonl/Stringer'>;
}
declare module 'stream-json/Parser.js' {
  declare module.exports: $Exports<'stream-json/Parser'>;
}
declare module 'stream-json/streamers/StreamArray.js' {
  declare module.exports: $Exports<'stream-json/streamers/StreamArray'>;
}
declare module 'stream-json/streamers/StreamBase.js' {
  declare module.exports: $Exports<'stream-json/streamers/StreamBase'>;
}
declare module 'stream-json/streamers/StreamObject.js' {
  declare module.exports: $Exports<'stream-json/streamers/StreamObject'>;
}
declare module 'stream-json/streamers/StreamValues.js' {
  declare module.exports: $Exports<'stream-json/streamers/StreamValues'>;
}
declare module 'stream-json/Stringer.js' {
  declare module.exports: $Exports<'stream-json/Stringer'>;
}
declare module 'stream-json/utils/Batch.js' {
  declare module.exports: $Exports<'stream-json/utils/Batch'>;
}
declare module 'stream-json/utils/emit.js' {
  declare module.exports: $Exports<'stream-json/utils/emit'>;
}
declare module 'stream-json/utils/Utf8Stream.js' {
  declare module.exports: $Exports<'stream-json/utils/Utf8Stream'>;
}
declare module 'stream-json/utils/Verifier.js' {
  declare module.exports: $Exports<'stream-json/utils/Verifier'>;
}
declare module 'stream-json/utils/withParser.js' {
  declare module.exports: $Exports<'stream-json/utils/withParser'>;
}
